### ISSUE TITLE
Bad response content type for SPARQL ASK queries

### ISSUE THREAD

**Issue by knoan** [openlink/virtuoso-opensource#464] opened 2015-08-20 09:58 UTC
As of Virtuoso/7.2.1, SPARQL ASK queries are answered with a `text/html` content type header.

```
 curl -v --data-urlencode 'query=ask {}' http://dbpedia.org/sparql

 > 
 * upload completely sent off: 18 out of 18 bytes
 < HTTP/1.1 200 OK
 < Content-Type: text/html; charset=UTF-8
 < Server: Virtuoso/07.20.3214 (Linux) x86_64-redhat-linux-gnu  VDB
 < 
 * Connection #0 to host dbpedia.org left intact
 true
```

`text/html` is definitely not congruent with the actual content and causes severe interoperability issues with Sesame, which would accept such a response with a `text/boolean` content type (even if according to the [standard](http://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#query-success) only XML, JSON or CSV/TSV would be acceptable).

Likely related to https://github.com/openlink/virtuoso-opensource/issues/214.

**Comment by HughWilliams** [comment] 2015-08-21 03:31
You say "as of" implying earlier versions of Virtuoso returned the correct content type header ? But when I check earlier releases they also return `text/html`, so what specific release have you seen the correct content type header with?

What are you expect to be returned, something like?

```
< Pragma: no-cache
< Content-Type: application/sparql-results+json; charset=utf-8
< Transfer-Encoding: chunked
< 
{ 
  "head" : { } ,
  "boolean" : true
}
```

**Comment by knoan** [comment] 2015-08-21 06:43
>  You say "as of" implying earlier versions of Virtuoso returned the correct content type header ? 

Probably not. I'm just reporting the version number for the observed issue.

> What are you expect to be returned, something like ?
> 
>   < Content-Type: application/sparql-results+json; charset=utf-8

That would be a legal answer according to the standard. A single `true` literal would also be accepted _de facto_ by Sesame, provided `Content-Type: text/boolean; charset=utf-8` is returned.

**Comment by zeginis** [comment] 2016-12-27 14:08
Is there any work around for this issue?
I am using rdf4j to access Virtuoso 7 and make `ASK` queries 
And I get a `406 Not Acceptable`. The same code works with version 6 of virtuoso
```
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>406 Not Acceptable</h1>
<p>An appropriate representation of the requested resource sparql could not be found on this server.</p>
Available variant(s):
<ul>
<li><a href="sparql">sparql</a> , type text/html, charset UTF-8</li>
</ul>
</body></html>
```

**Comment by HughWilliams** [comment] 2016-12-27 14:41
Virtuoso 6 returns the same `Content-Type: text/html; charset=UTF-8` as Virtuoso 7 ...

```
$ curl -v --data-urlencode 'query=ask {}' http://localhost:8890/sparql
.
.
.
> 
* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 200 OK
< Server: Virtuoso/06.01.3127 (Darwin) x86_64-apple-darwin12.5.0  
< Connection: Keep-Alive
< Date: Tue, 27 Dec 2016 14:30:57 GMT
< Accept-Ranges: bytes
< Content-Type: text/html; charset=UTF-8
< Content-Length: 4
< 
* Connection #0 to host localhost left intact
$
```

Thus what is a simple recreateable test case for the problem you are encountering ?

**Comment by zeginis** [comment] 2016-12-27 14:59
Hi @HughWilliams,

Thank you for the prompt answer.

I use rdf4j library. The same code works ok for Virtuoso 6 while it does not work with Virtuoso 7.
The code is: 
```
String endpointUrl="MYVIRTUOSO/sparql"; //virtuoso SPARQL ENDPOINT
String queryString="ASK where {?x ?y ?z}";
Repository repo = new SPARQLRepository(endpointUrl);
repo.initialize();
RepositoryConnection con = repo.getConnection();		
BooleanQuery booleanQuery = con.prepareBooleanQuery(QueryLanguage.SPARQL, queryString);		
boolean result;
try {
	result= booleanQuery.evaluate();	
} catch (Exception e) {
	e.printStackTrace();
} 

```
The exception I get is:

```
org.eclipse.rdf4j.query.QueryEvaluationException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>406 Not Acceptable</h1>
<p>An appropriate representation of the requested resource sparql could not be found on this server.</p>
Available variant(s):
<ul>
<li><a href="sparql">sparql</a> , type text/html, charset UTF-8</li>
</ul>
</body></html>
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLBooleanQuery.evaluate(SPARQLBooleanQuery.java:45)
	at org.certh.jsonqb.api.test.main(test.java:27)
Caused by: org.eclipse.rdf4j.repository.RepositoryException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>406 Not Acceptable</h1>
<p>An appropriate representation of the requested resource sparql could not be found on this server.</p>
Available variant(s):
<ul>
<li><a href="sparql">sparql</a> , type text/html, charset UTF-8</li>
</ul>
</body></html>
	at org.eclipse.rdf4j.http.client.SparqlSession.execute(SparqlSession.java:1132)
	at org.eclipse.rdf4j.http.client.SparqlSession.executeOK(SparqlSession.java:1056)
	at org.eclipse.rdf4j.http.client.SparqlSession.sendBooleanQueryViaHttp(SparqlSession.java:1042)
	at org.eclipse.rdf4j.http.client.SparqlSession.getBoolean(SparqlSession.java:988)
	at org.eclipse.rdf4j.http.client.SparqlSession.sendBooleanQuery(SparqlSession.java:486)
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLBooleanQuery.evaluate(SPARQLBooleanQuery.java:38)
	... 1 more
```

**Comment by HughWilliams** [comment] 2016-12-27 22:44
@zeginis : How do you compile and run this sample code ... what imports and class/jar files are required ?

**Comment by zeginis** [comment] 2016-12-28 08:14
@HughWilliams  the code with the imports:
```
import org.eclipse.rdf4j.query.BooleanQuery;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sparql.SPARQLRepository;

public class rdf4jtest {
public static void main (String args[]){
	String endpointUrl="MYVIRTUOSO/sparql"; //virtuoso SPARQL ENDPOINT
	String queryString="ASK where {?x ?y ?z}";
	Repository repo = new SPARQLRepository(endpointUrl);
	repo.initialize();
	RepositoryConnection con = repo.getConnection();		
	BooleanQuery booleanQuery = con.prepareBooleanQuery(QueryLanguage.SPARQL, queryString);
		
	boolean result;
	try {
		result= booleanQuery.evaluate();	
		System.out.println(result);
	} catch (Exception e) {
		e.printStackTrace();
	} 	
   }
}
```

For the jar you just need to include RDF4J as a Maven dependency in your Java project
http://rdf4j.org/download/

This is my pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.certh.opencube</groupId>
  <artifactId>test</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>test</name>
  <url>http://maven.apache.org</url>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <dependencyManagement>
	<dependencies>
	 <dependency>
	 	<groupId>org.eclipse.rdf4j</groupId>
		<artifactId>rdf4j-bom</artifactId>
		<version>2.1.4</version>
		<type>pom</type>
		<scope>import</scope>
	 </dependency>
	</dependencies>
</dependencyManagement>
 <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
	<groupId>org.eclipse.rdf4j</groupId>
	<artifactId>rdf4j-runtime</artifactId>
    </dependency>  
  </dependencies>
</project>
```

Thank you

**Comment by HughWilliams** [comment] 2016-12-29 18:13
@zeginis: I don't use java  IDE's and pom files as they depressingly never work for me, not being a Java programmer ... so I compile and run from command line and find that the same issue occurs with a Virtuoso 6.x build:

```
Hughs-MBP-2:database hwilliams$ /Users/hwilliams/src/git/vos-6-develop/binsrc/virtuoso/virtuoso-t -?
Virtuoso Open Source Edition (Row Store) (multi threaded)
Version 6.1.9-dev.3127-pthreads as of May 30 2014
Compiled for Darwin (x86_64-apple-darwin12.5.0)
Copyright (C) 1998-2014 OpenLink Software
```

```
Hughs-MBP-2:rdf4j hwilliams$ cat rdf4jtest.java 
import org.eclipse.rdf4j.query.BooleanQuery;
import org.eclipse.rdf4j.query.QueryLanguage;
import org.eclipse.rdf4j.repository.Repository;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sparql.SPARQLRepository;

public class rdf4jtest {
public static void main (String args[]){
	String endpointUrl="http://localhost:8890/sparql"; //virtuoso SPARQL ENDPOINT
	String queryString="ASK where {?x ?y ?z}";
	Repository repo = new SPARQLRepository(endpointUrl);
	repo.initialize();
	RepositoryConnection con = repo.getConnection();		
	BooleanQuery booleanQuery = con.prepareBooleanQuery(QueryLanguage.SPARQL, queryString);
		
	boolean result;
	try {
		result= booleanQuery.evaluate();	
		System.out.println(result);
	} catch (Exception e) {
		e.printStackTrace();
	} 	
   }
}
Hughs-MBP-2:rdf4j hwilliams$ 
```

For which running the program returns the same error as when run against a Virtuoso 7 instance i.e.

```
Hughs-MBP-2:rdf4j hwilliams$ javac -cp ".:./eclipse-rdf4j-2.0.1-onejar.jar:./slf4j-api-1.7.10.jar:./commons-io-2.4.jar:httpcore-4.3.2.jar:httpclient-4.3.4.jar:google-collections-1.0-sources.jar:google_common_deploy.jar:commons-logging-1.1.3.jar" rdf4jtest.java 
Hughs-MBP-2:rdf4j hwilliams$ java -cp ".:./eclipse-rdf4j-2.0.1-onejar.jar:./slf4j-api-1.7.10.jar:./commons-io-2.4.jar:httpcore-4.3.2.jar:httpclient-4.3.4.jar:google-collections-1.0-sources.jar:google_common_deploy.jar:commons-logging-1.1.3.jar" rdf4jtest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
org.eclipse.rdf4j.query.QueryEvaluationException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>406 Not Acceptable</h1>
<p>An appropriate representation of the requested resource sparql could not be found on this server.</p>
Available variant(s):
<ul>
<li><a href="sparql">sparql</a> , type text/html, charset UTF-8</li>
</ul>
</body></html>
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLBooleanQuery.evaluate(SPARQLBooleanQuery.java:45)
	at rdf4jtest.main(rdf4jtest.java:18)
Caused by: org.eclipse.rdf4j.repository.RepositoryException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>406 Not Acceptable</h1>
<p>An appropriate representation of the requested resource sparql could not be found on this server.</p>
Available variant(s):
<ul>
<li><a href="sparql">sparql</a> , type text/html, charset UTF-8</li>
</ul>
</body></html>
	at org.eclipse.rdf4j.http.client.SparqlSession.execute(SparqlSession.java:1132)
	at org.eclipse.rdf4j.http.client.SparqlSession.executeOK(SparqlSession.java:1056)
	at org.eclipse.rdf4j.http.client.SparqlSession.sendBooleanQueryViaHttp(SparqlSession.java:1042)
	at org.eclipse.rdf4j.http.client.SparqlSession.getBoolean(SparqlSession.java:988)
	at org.eclipse.rdf4j.http.client.SparqlSession.sendBooleanQuery(SparqlSession.java:486)
	at org.eclipse.rdf4j.repository.sparql.query.SPARQLBooleanQuery.evaluate(SPARQLBooleanQuery.java:38)
	... 1 more
Hughs-MBP-2:rdf4j hwilliams$ 
```

Thus was is the Virtuoso 6 version and build date you are using (virtuoso-t -?) ?

**Comment by zeginis** [comment] 2016-12-30 12:10
Hi @HughWilliams  

This is my Version 6 build

```
Virtuoso Open Source Edition (multi threaded)
Version 6.1.8.3127-threads as of Dec 11 2013
Compiled for Win64 (x86_64-generic-win-64)
Copyright (C) 1998-2013 OpenLink Software
```

**Comment by HughWilliams** [comment] 2016-12-30 15:58
@zeginis: with the 6.1.8 build I have been able to get the RDF4J app to run:

```
Hughs-MBP-2:rdf4j hwilliams$ java -cp ".:./eclipse-rdf4j-2.0.1-onejar.jar:./slf4j-api-1.7.10.jar:./commons-io-2.4.jar:httpcore-4.3.2.jar:httpclient-4.3.4.jar:google-collections-1.0-sources.jar:google_common_deploy.jar:commons-logging-1.1.3.jar:com.fasterxml.jackson.core.jar" rdf4jtest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
true
Hughs-MBP-2:rdf4j hwilliams$
```

Although I note that running the curl query provided by the original creator of this git issue the 6.1.8 build returns the same "text/html" content header type as 6.1.9 & 7.2 do:

```
Hughs-MBP-2:rdf4j hwilliams$ curl -v --data-urlencode 'query=ask {}' http://opluswin7qa.usnet.private:8890/sparql
*   Trying 192.168.11.16...
* Connected to opluswin7qa.usnet.private (192.168.11.16) port 8890 (#0)
> POST /sparql HTTP/1.1
> Host: opluswin7qa.usnet.private:8890
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 18
> Content-Type: application/x-www-form-urlencoded
> 

* upload completely sent off: 18 out of 18 bytes
< HTTP/1.1 200 OK
< Server: Virtuoso/06.01.3127 (Win64) x86_64-generic-win-64  
< Connection: Keep-Alive
< Date: Fri, 30 Dec 2016 15:45:58 GMT
< Accept-Ranges: bytes
< Content-Type: text/html; charset=UTF-8
< Content-Length: 4
< 
* Connection #0 to host opluswin7qa.usnet.private left intact
true
Hughs-MBP-2:rdf4j hwilliams$
```

So the "text/boolean" content header type response is not the solution as they propose ... as seems it is something else in the response being returned that is causing the HTTP "406 Not Acceptable" in RDF4J ...

Thus have reported this to development to look into and determine what has changed been 6.1.8 & 6.1.9 (or 7.1 & 7.2) Virtuoso versions ...

**Comment by zeginis** [comment] 2016-12-30 16:26
Thank you @HughWilliams .

**Comment by tfrancart** [comment] 2017-10-04 10:34
Hello I am facing the same issue in SKOS Play (http://labs.sparna.fr/skos-play), that relies on RDF4J : when pointing SKOS Play to the URL of a Virtuoso SPARQL endpoint, all the SPARQL ASK queries fail.
Do we have an update on this issue ?

**Comment by HughWilliams** [comment] 2017-10-14 22:03
The is no update on this issue yet, which is still to be looked into by development ...

**Comment by saleem-muhammad** [comment] 2018-01-04 02:42
Now I am also facing the same issue. any fixes yet?

**Comment by zeginis** [comment] 2018-08-14 12:57
Any update on this? It has passed more than 2 year and the bug still exists.

**Comment by HughWilliams** [comment] 2018-08-14 13:47
There is no resolution to this issue yet, which is still to be looked into by development ...

**Comment by TallTed** [comment] 2018-08-14 14:36
@zeginis, @saleem-muhammad, @tfrancart, @knoan --

The originally reported issue does persist in current Virtuoso 7 and Virtuoso 8 (both of which I've just tested).  The default response content type for `ASK` queries is currently `text/html` (though the literal content is just 4 characters, `true`), where [the spec says](http://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#query-success) it should be a "SPARQL Results Document in [XML](http://www.w3.org/TR/rdf-sparql-XMLres/), [JSON](http://www.w3.org/TR/sparql11-results-json/), or [CSV/TSV](http://www.w3.org/TR/sparql11-results-csv-tsv/) format", as demonstrated by --

`curl -v --data-urlencode 'query=ask {}' http://dbpedia.org/sparql`

There **is** a workaround with current Virtuoso 7 and Virtuoso 8 (which I've just tested; I have not tested earlier versions) if the client explicitly requests one of those content types.  All of the following deliver the output as requested:

- `curl -v -H "Accept: application/sparql-results+xml" --data-urlencode 'query=ask {}' http://dbpedia.org/sparql`
- `curl -v -H "Accept: application/sparql-results+json" --data-urlencode 'query=ask {}' http://dbpedia.org/sparql`
- `curl -v -H "Accept: text/csv" --data-urlencode 'query=ask {}' http://dbpedia.org/sparql`
- `curl -v -H "Accept: text/tab-separated-values" --data-urlencode 'query=ask {}' http://dbpedia.org/sparql`


I can only guess that the RDF4J/Sesame clients are not including an `Accept:` request header, though the [spec says they SHOULD](https://www.w3.org/TR/2013/REC-sparql11-protocol-20130321/#conneg).

I am not an active user of RDF4J/Sesame, and I've not been quickly able to find any info about the default request headers it emits, nor whether you can force them, and if so, how.  Hopefully this info helps lead you to a workaround while Virtuoso's default response is being addressed.

**Comment by TallTed** [comment] 2018-08-14 20:23
@zeginis, @saleem-muhammad, @tfrancart, @knoan --

Also see my update to #214.

**Comment by kuzeko** [comment] 2021-06-09 18:16
For those passing by here trying to execute `ASK` queries with RDF4J over Virtuoso , the code snippet solving the issue is:

```
SPARQLRepository repo = new SPARQLRepository(host);
Map<String, String> headers =new HashMap<>();
headers.put("Accept", "application/sparql-results+json");
repo.setAdditionalHttpHeaders(headers);

```

Thanks to @TallTed

**Comment by TallTed** [comment] 2021-06-09 20:33
@pkleef @openlink @HughWilliams -- Please see above, https://github.com/openlink/virtuoso-opensource/issues/464#issuecomment-412894503, for a sometimes viable workaround (just confirmed in the latest comment above), but note that the final resolution of this six year old issue should be a change in the default media type Virtuoso uses for responses to `ASK` queries.

**Comment by HughWilliams** [comment] 2024-08-05 16:21
This issue is resolved in the latest VOS build:

```shell
$ java -cp ".:./eclipse-rdf4j-2.0.1-onejar.jar:./slf4j-api-1.7.10.jar:./commons-io-2.4.jar:httpcore-4.3.2.jar:httpclient-4.3.4.jar:google-collections-1.0-sources.jar:google_common_deploy.jar:commons-logging-1.1.3.jar:com.fasterxml.jackson.core.jar" rdf4jtest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
true
$
```

**Closed as completed by HughWilliams** 2024-08-05 16:21 UTC
