### ISSUE TITLE
UUID() and STRUUID() evaluated once per query rather than once per binding

### ISSUE THREAD

**Issue by jindrichmynarz** [openlink/virtuoso-opensource#515] opened 2015-12-30 10:11 UTC
If you execute a query that uses `UUID()` or `STRUUID()` the same UUID is generated for each binding. For example (tested on Virtuoso 07.20.3215):

```
SELECT ?s ?p ?o (STRUUID() AS ?uuid)
WHERE {
  ?s ?p ?o .
}
LIMIT 10
```

This leads me to believe that the UUID functions are evaluated only once per query execution rather than once per each query binding. The [SPARQL specification](http://www.w3.org/TR/sparql11-query/#func-uuid) says that _"Each call of UUID() returns a different UUID."_ It seems that Virtuoso violates that. Moreover, I think previous versions of Virtuoso implemented this correctly, so it may be a regression.

**Comment by HughWilliams** [comment] 2015-12-30 16:10
@jindrichmynarz: Works fine for me with each execution returning a different UUID ...

```
SQL> SPARQL SELECT ?s ?p ?o (STRUUID() AS ?uuid) WHERE {   ?s ?p ?o . } LIMIT 2; 
s                                                                                 p                                                                                 o                                                                                 uuid
LONG VARCHAR                                                                      LONG VARCHAR                                                                      LONG VARCHAR                                                                      VARCHAR
_______________________________________________________________________________

http://www.openlinksw.com/virtrdf-data-formats#default-iid                        http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat                           8CE00A58-AF0D-11E5-9AD7-C8463BEB0D19
http://www.openlinksw.com/virtrdf-data-formats#default-iid-nullable               http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat                           8CE00A58-AF0D-11E5-9AD7-C8463BEB0D19

2 Rows. -- 3 msec.
SQL> SQL> SPARQL SELECT ?s ?p ?o (STRUUID() AS ?uuid) WHERE {   ?s ?p ?o . } LIMIT 2;
s                                                                                 p                                                                                 o                                                                                 uuid
LONG VARCHAR                                                                      LONG VARCHAR                                                                      LONG VARCHAR                                                                      VARCHAR
_______________________________________________________________________________

http://www.openlinksw.com/virtrdf-data-formats#default-iid                        http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat                           97009E76-AF0D-11E5-9AD7-C8463BEB0D19
http://www.openlinksw.com/virtrdf-data-formats#default-iid-nullable               http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat                           97009E76-AF0D-11E5-9AD7-C8463BEB0D19

2 Rows. -- 1 msec.
SQL> SPARQL SELECT ?s ?p ?o (STRUUID() AS ?uuid) WHERE {   ?s ?p ?o . } LIMIT 2;
s                                                                                 p                                                                                 o                                                                                 uuid
LONG VARCHAR                                                                      LONG VARCHAR                                                                      LONG VARCHAR                                                                      VARCHAR
_______________________________________________________________________________

http://www.openlinksw.com/virtrdf-data-formats#default-iid                        http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat                           9BEF4874-AF0D-11E5-9AD7-C8463BEB0D19
http://www.openlinksw.com/virtrdf-data-formats#default-iid-nullable               http://www.w3.org/1999/02/22-rdf-syntax-ns#type                                   http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat                           9BEF4874-AF0D-11E5-9AD7-C8463BEB0D19

2 Rows. -- 0 msec.
SQL> status('');
REPORT
VARCHAR
_______________________________________________________________________________

OpenLink Virtuoso  Server
Version 07.20.3215-pthreads for Darwin as of Dec 30 2015 
Started on: 2015-12-30 15:35 GMT+0
```

**Comment by jindrichmynarz** [comment] 2015-12-30 17:00
Yes, it returns a different UUID per each query execution. The issue is that the generated UUIDs are the same for each binding in the result set.

**Comment by jindrichmynarz** [comment] 2015-12-30 17:06
For example, try this query:

```
SELECT (STRUUID() AS ?uuid)
WHERE { VALUES ?line { 1 2 3 4 5 } }
```

Using Virtuoso, all 5 generated UUIDs are the same. Using Apache Jena Fuseki, each UUID is distinct (see [here](http://sparql.org/books/sparql?query=SELECT+%28STRUUID%28%29+AS+%3Fuuid%29%0D%0AWHERE+%7B+VALUES+%3Fline+%7B+0+1+2+3+4+%7D+%7D&output=text&stylesheet=%2Fxml-to-html.xsl)).

**Comment by HughWilliams** [comment] 2015-12-30 17:37
@jindrichmynarz: OK, I misread your description. I can see the problem now and have reported to development ...

**Comment by Polymathronic** [comment] 2016-01-19 10:52
+1. Any updates?

**Comment by openlink** [comment] 2016-01-19 13:20
Development is working on a fix which will hopefully be committed soon.

**Comment by jindrichmynarz** [comment] 2016-04-07 07:51
Is there a progress on this issue?

**Comment by irygaev** [comment] 2016-04-29 13:49
The same issue is with `bif:next_sequence` function

**Comment by Polymathronic** [comment] 2016-08-24 14:01
Has this been resolved?

**Comment by HughWilliams** [comment] 2016-08-26 23:32
This issue is still to be resolved ...

**Comment by jindrichmynarz** [comment] 2016-11-01 10:45
This is still an issue in 377438ac6beefa9373cf0500c7edf4077f687d0c.

**Comment by yyz1989** [comment] 2017-02-08 16:11
is it still open?

**Comment by jindrichmynarz** [comment] 2017-04-17 14:56
Still an issue in 07.20.3217.

**Comment by HughWilliams** [comment] 2017-04-22 19:09
Chased development of update on fix for this issue ...

**Comment by jakubklimek** [comment] 2017-09-08 07:18
Any news?

**Comment by ghost** [comment] 2017-11-06 11:44
Any update?

**Comment by boutros** [comment] 2018-07-05 08:59
Would be great to have this fixed. Any pointers to where to look in the code if I where to have a go at it?

**Comment by nvdk** [comment] 2019-01-23 15:37
we ran into this as well. for those interested you can use the following construct as a workaround. This will cause `STRUUID` to be evaluated for each row.
```
OPTIONAL { ?s mu:uuid ?uuid } BIND(IF(BOUND(?uuid), ?uuid, STRUUID()) as ?realUUID)
```
hat tip to @Rahien

**Comment by rwynne** [comment] 2019-05-02 19:27
What would it take for `bif:UUID()` to be called in a function that is processed over and over within a query?  It requires a value.

Example:

```BIND(IRI(CONCAT('<namespace>#foo-', bif:uuid(?bar_value))) as ?my_result)```

**Comment by HughWilliams** [comment] 2019-05-29 16:19
@rwynne - Not sure what you are asking, please provide a specific demonstrable example ...

**Comment by namedgraph** [comment] 2019-10-26 15:23
https://github.com/openlink/virtuoso-opensource/issues/515

**Comment by kidehen** [comment] 2019-10-27 16:42
> This is still an issue in [377438a](https://github.com/openlink/virtuoso-opensource/commit/377438ac6beefa9373cf0500c7edf4077f687d0c).

It is an issue in the Open Source edition rather than the Commercial Edition.
```
SELECT DISTINCT  (STRUUID() AS ?strUUID) (UUID() AS ?UUID)
WHERE {
        [] a ?o . 
      }

LIMIT 10
```

SeeAlso [Live Query Solution Page](http://linkeddata.uriburner.com/sparql?default-graph-uri=&query=SELECT+DISTINCT++%28STRUUID%28%29+AS+%3FstrUUID%29+%28UUID%28%29+AS+%3FUUID%29%0D%0AWHERE+%7B%0D%0A++++++++%5B%5D+a+%3Fo+.+%0D%0A++++++%7D%0D%0A%0D%0ALIMIT+10&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000000) -- based on the Commercial Edition. 

/cc @HughWilliams

**Comment by TallTed** [comment] 2019-10-28 17:43
@kidehen /cc @HughWilliams 

To be clear, the issue is resolved in Commercial/Enterprise Edition `v08.03.3315` (9c4e63d226) built 2019-10-25, if not earlier, as seen [here](http://linkeddata.uriburner.com/sparql?default-graph-uri=&query=SELECT+DISTINCT++%28STRUUID%28%29+AS+%3FstrUUID%29+%28UUID%28%29+AS+%3FUUID%29%0D%0AWHERE+%7B%0D%0A++++++++%5B%5D+a+%3Fo+.+%0D%0A++++++%7D%0D%0A%0D%0ALIMIT+10&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000000) (your link), which has 10 unique `strUUID` and 10 unique  `UUID`.

It persists in Commercial/Enterprise Edition `v07.20.3232` (2afcc45d7c) built 2019-08-09, if not later, as seen [here](http://dbpedia.org/sparql?default-graph-uri=&query=SELECT+DISTINCT++%28STRUUID%28%29+AS+%3FstrUUID%29+%28UUID%28%29+AS+%3FUUID%29%0D%0AWHERE+%7B%0D%0A++++++++%5B%5D+a+%3Fo+.+%0D%0A++++++%7D%0D%0A%0D%0ALIMIT+10&format=text%2Fhtml&timeout=30000000&debug=on&run=+Run+Query+), which has 10 unique `strUUID` and 1 `UUID` repeated 10 times.

**Comment by mwahle** [comment] 2023-07-03 17:57
Just ran into this problem on the open source Virtuoso. It displays version 07.20.3236, Build Feb 27 2023. All generated UUIDs in a result set are the same.

**Comment by pkleef** [comment] 2023-07-04 10:56
According our internal documentation this was fixed in commit 3744765616bf7e7c42eb00512ad62e1d9385172a

Can you show us the query you used to confirm it was not fixed for you?

**Comment by mwahle** [comment] 2023-07-04 15:43
@pkleef Hi Patrick, on our instance, both queries posted in this thread return a constant UUID. Also, as of today, @kidehen's [link](http://linkeddata.uriburner.com/sparql?default-graph-uri=&query=SELECT+DISTINCT++%28STRUUID%28%29+AS+%3FstrUUID%29+%28UUID%28%29+AS+%3FUUID%29%0D%0AWHERE+%7B%0D%0A++++++++%5B%5D+a+%3Fo+.+%0D%0A++++++%7D%0D%0A%0D%0ALIMIT+10&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000000) shows a constant UUID.

**Comment by pkleef** [comment] 2023-07-07 09:11
i checked the [Virtuoso Enterprise Edition on uriburner](http://linkeddata.uriburner.com/sparql?default-graph-uri=&query=SELECT+DISTINCT++%28STRUUID%28%29+AS+%3FstrUUID%29+%28UUID%28%29+AS+%3FUUID%29%0D%0AWHERE+%7B%0D%0A++++++++%5B%5D+a+%3Fo+.+%0D%0A++++++%7D%0D%0A%0D%0ALIMIT+10&should-sponge=&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000000) you mentioned and it clearly shows unique UUIDs on all rows.

I assume you meant you ran the same query against your VOS instance, which i have confirmed indeed  still returns a constant UUID value.

I am finalizing a fix for VOS which should be pushed to develop/7 shortly.

**Closed as completed** 2023-07-07 14:48 UTC

**Comment by mwahle** [comment] 2023-07-09 01:28
Yes you are right, those UUIDs on uriburner are unique. Used to UUIDs v4, so overlooked those rather subtle differences, sorry...

I do thank you for your responsiveness - great initial experience. We just started using VOS. Looking forward!
