### ISSUE TITLE
errors when compiling virtuoso open-source

### ISSUE THREAD

**Issue by pfps** [openlink/virtuoso-opensource#1324] opened 2024-10-26 13:46 UTC
On an up-to-date Fedora 40 distribution I get the following compiler error from the make process:

```
ncfg.c:172:18: error: assignment to 'char *' from incompatible pointer type 'PCFGENTRY' {aka 'struct TCFGENTRY *'} [-Wincompatible-pointer-types]
  172 |   pconfig->image = pconfig->entries = NULL;
      |                  ^
```

The easy patch appears to work but then there is:

```
Dksesstr.c:1793:37: warning: cast between incompatible function types from 'void (*)(char *, dk_session_t *)' {aka 'void (*)(char *, struct dk_session_s *)'} to 'int (*)(const void *, dk_session_t *)' {aka 'int (*)(const void *, struct dk_session_s *)'} [-Wcast-function-type]
 1793 |   PrpcSetWriter (DV_STRING_SESSION, (ses_write_func) strses_serialize);
      |                                     ^
```
The required patch is not obvious.

**Comment by pkleef** [comment] 2024-10-26 14:39
We are working on a patch that will solve this.

**Comment by pfps** [comment] 2024-10-26 16:19
Using `CFLAGS` as `-O2 -m64` produces a different error:

```
Dksesstr.c:710:41: error: passing argument 2 of 'virt_mbsnrtowcs' from incompatible pointer type [-Wincompatible-pointer-types]
  710 |       last_len = virt_mbsnrtowcs (NULL, &ptr, ses->dks_out_fill, 0, &mb);
      |                                         ^~~~
      |                                         |
      |                                         unsigned char **
```

**Comment by pkleef** [comment] 2024-10-28 13:50
The issue is that in GCC version 14.x and later, they changed a compiler flag from producing a warning, to producing an error when pointer types do not exactly match. Parts of the Virtuoso source code are very old, and written using an older version of the C standard that did not always properly check for such constructions. 

As newer GNU C compilers get more advanced in detecting possible error-prone constructions, our development teams are adding more CI (continuous integration) VMs to test different Linux distributions. However, due to resource constraints, our prime focus is on making sure Virtuoso runs on a number of established LTS (long term support) distributions from RedHat, Debian, and Ubuntu. 

However, if users such as yourself report a distribution that is not adequately supported, we will schedule time to fix the reported issues.

We are currently working on a fix to solve the issues reported by the GCC v14.x compiler, which will be part of the upcoming next stable release we hope to release in the next couple of weeks.

In the meantime, you can use the following command as a workaround:

```
$ env CFLAGS="-Wno-incompatible-pointer-types" \
    ./configure \
        --enable-maintainer-mode \
        --prefix=/opt/virtuoso-opensource \
        --with-layout=openlink \
        --enable-openssl \
        --with-pthreads
```

I have just tested this solution on FC40 and this produces a virtuoso build that fully passes the test suite.

**Closed as completed** 2024-11-07 13:19 UTC

**Comment by pfps** [comment] 2024-11-13 21:21
Seems to have done the trick,  Thanks.
