### ISSUE TITLE
GPF: sqlrun.c:3310 musta forgotten branch copy of set no ssl for fref

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#200] opened 2014-06-19 13:30 UTC
The query:

<pre><code>
PREFIX r: &lt;http://ruian.linked.opendata.cz/ontology/&gt;
prefix s: &lt;http://schema.org/&gt;
select distinct count(?name) where {
  ?ulice rdf:type r:Ulice;
        s:name ?name.
}</code></pre>

crashes our Virtuoso instance based on 8173801092e9fd4abc06d32e642e6d7d72b4bf40 

<a href="http://ruian.linked.opendata.cz/ruian-2014-06-19.zip">Instance data (7,5GB)</a>

virtuoso.log:

<pre><code>14:36:57 /usr/local/bin/virtuoso-t() [0x9202ba]
14:36:57 /usr/local/bin/virtuoso-t() [0x920326]
14:36:57 /usr/local/bin/virtuoso-t() [0x61a9e8]
14:36:57 /usr/local/bin/virtuoso-t() [0x61aada]
14:36:57 /usr/local/bin/virtuoso-t() [0x654f21]
14:36:57 /usr/local/bin/virtuoso-t() [0x656882]
14:36:57 /usr/local/bin/virtuoso-t() [0x616df9]
14:36:57 /usr/local/bin/virtuoso-t(table_source_input+0x284) [0x620684]
14:36:57 /usr/local/bin/virtuoso-t() [0x615992]
14:36:57 /usr/local/bin/virtuoso-t(fun_ref_node_input+0xd5) [0x61ad55]
14:36:57 /usr/local/bin/virtuoso-t() [0x615992]
14:36:57 /usr/local/bin/virtuoso-t() [0x615c9e]
14:36:57 /usr/local/bin/virtuoso-t() [0x64da80]
14:36:57 /usr/local/bin/virtuoso-t() [0x615992]
14:36:57 /usr/local/bin/virtuoso-t() [0x615c9e]
14:36:57 /usr/local/bin/virtuoso-t() [0x64da80]
14:36:57 /usr/local/bin/virtuoso-t() [0x615992]
14:36:57 /usr/local/bin/virtuoso-t() [0x61f596]
14:36:57 /usr/local/bin/virtuoso-t(bif_exec+0x5f1) [0x58b491]
14:36:57 /usr/local/bin/virtuoso-t() [0x5e74b8]
14:36:57 /usr/local/bin/virtuoso-t() [0x5ef9c2]
14:36:57 /usr/local/bin/virtuoso-t() [0x615a3a]
14:36:57 /usr/local/bin/virtuoso-t() [0x61e0ec]
14:36:57 /usr/local/bin/virtuoso-t() [0x5e7b36]
14:36:57 /usr/local/bin/virtuoso-t() [0x5efd8b]
14:36:57 /usr/local/bin/virtuoso-t() [0x615a3a]
14:36:57 /usr/local/bin/virtuoso-t() [0x61e0ec]
14:36:57 /usr/local/bin/virtuoso-t() [0x5e7b36]
14:36:57 /usr/local/bin/virtuoso-t() [0x5e8b9b]
14:36:57 /usr/local/bin/virtuoso-t() [0x5ed60c]
14:36:57 /usr/local/bin/virtuoso-t() [0x61597b]
14:36:57 /usr/local/bin/virtuoso-t() [0x61f596]
14:36:57 /usr/local/bin/virtuoso-t() [0x62182d]
14:36:57 /usr/local/bin/virtuoso-t() [0x720fe4]
14:36:57 /usr/local/bin/virtuoso-t() [0x5006a8]
14:36:57 /usr/local/bin/virtuoso-t() [0x502024]
14:36:57 /usr/local/bin/virtuoso-t() [0x50227c]
14:36:57 /usr/local/bin/virtuoso-t(ws_init_func+0x8e) [0x50268e]
14:36:57 /usr/local/bin/virtuoso-t() [0x9283bf]
14:36:57 /lib/x86_64-linux-gnu/libpthread.so.0(+0x6b50) [0x7fd5ae7c7b50]
14:36:57 /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fd5ae08c0ed]
14:36:57 GPF: sqlrun.c:3310 musta forgotten branch copy of set no ssl for fref
</code></pre>

**Comment by HughWilliams** [comment] 2014-06-23 23:42
I have downloaded the database and been able to recreate locally. This has been reported to development to fix, internal issue tracker #16193 ...

**Comment by alexandrutodor** [comment] 2015-01-03 16:42
Hi,

This bug is actively being used to crash the German DBpedia endpoint multiple times per day. I would kindly ask to know if this issue has been patched or if a workaround exists.

Cheers,
Alexandru

**Comment by HughWilliams** [comment] 2015-01-04 00:53
The problem is resolved in the latest git develop/7 branch (https://github.com/openlink/virtuoso-opensource):

SQL> SPARQL PREFIX r: http://ruian.linked.opendata.cz/ontology/ prefix s: http://schema.org/ select distinct count(?name) where {   ?ulice rdf:type r:Ulice;         s:name ?name. };
callret-0
INTEGER

---

63599

1 Rows. -- 5 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.10.3211-pthreads for Linux as of Dec 11 2014 
Started on: 2015-01-04 01:39 GMT+1

**Closed as completed by HughWilliams** 2015-01-04 00:53 UTC
