### ISSUE TITLE
How to avoid checkpoints in Virtuoso?

### ISSUE THREAD

**Issue by kotheoha** [openlink/virtuoso-opensource#723] opened 2018-03-03 20:42 UTC
Hi,

Is there a way to avoid checkpoints during a big series of queries in Virtuoso? I would like after executing all the queries, to do manually one checkpoint in the end. Right now, Virtuoso automatically do checkpoints and make unfair the execution time among queries.

Best,
KT.

**Comment by HughWilliams** [comment] 2018-03-04 00:05
@kotheoha: The `checkpoint_interval(-1)` function can be used to dynamically disable checkpointing  which can the reset to occur automatically at a specified interval using the same function as detailed at:

   http://docs.openlinksw.com/virtuoso/fn_checkpoint_interval/

**Comment by kotheoha** [comment] 2018-03-04 11:21
Hi,

Ok, still is there any risk to my queries validity results if I disable all checkpoints? How a checkpoint is related with the database (graph) that my queries modify?

In other words, If I have a graph G, a checkpoint C,  PREV = {set of queries before C that modify G} , NEXT = {set of queries after C that modify G}, I would achieve the same result by enabling or disabling C?

Generally, when someone like me wants to measure execution time of Virtuoso in a series of queries that each one of them modifies G (so G must be read right by the queries that follow), must include or not checkpoint in execution time? If checkpoint is part of Virtuoso mechanism that ensures validity in G, then checkpoint must be included. What do you propose? What is the formal suggestion by the Virtuoso team to measure execution time in experiments like mine? 

Best,
KT.

**Comment by HughWilliams** [comment] 2018-03-04 12:28
@kotheoha: Not sure what you are asking ... checkpoint simply controls when the transactions in the "virtuoso.trx"  (transaction log file) since the last checkpoint are committed to the virtuoso.db ( virtuoso database file ) , but does not affect  graph/rdf or SQL behaviour. 

The main reason people disable checkpointing when performing long/bulk query activities is because checkpointing is an atomic operation during which the database is inaccessible and hence can result in delays in performing operation whilst in progress ...

**Comment by HughWilliams** [comment] 2018-03-04 12:33
also read: http://docs.openlinksw.com/virtuoso/checkpointparams/

**Comment by kotheoha** [comment] 2018-03-06 12:47
In http://docs.openlinksw.com/virtuoso/fn_checkpoint_interval/ it is mentioned that:
By setting checkpoint interval to 0, the checkpoint will only be performed after roll forward upon database startup. A setting of -1 will disable all checkpointing.

So, I set CheckpointInterval = -1 to the virtuoso.ini file. I performed a series of long/bulk query activities and the system did not make checkpointing as I wanted. However, when I restart the Virtuoso server it starts a roll forward like:

....
14:01:27     13086000 transactions, 588888933 bytes replayed (4 %)
14:01:29     13103000 transactions, 589653963 bytes replayed (4 %)
14:01:31     13120000 transactions, 590418963 bytes replayed (4 %)
14:01:33     13137000 transactions, 591183993 bytes replayed (4 %)
14:01:35     13154000 transactions, 591948993 bytes replayed (4 %)
....

Since as I have set checkpoint to -1 and not to 0 why happens that? It seems that I must wait a whole day so as to proceed to my next series of long/bulk query activities! How can I avoid above transactions when Virtuoso restarts without waiting?

Best,
KT.

**Comment by TallTed** [comment] 2018-03-06 15:04
The transaction log, `virtuoso.trx`, will continue to grow and accumulate transactions — which will need to be replayed at each instance launch — until a checkpoint is run.

I would recommend that you —
1. set `CheckpointInterval = -1`
2. run your bulk inserts and other changes
3. manually run a `checkpoint;` before you shut down the instance
4. set `CheckpointInterval = 360` or something else more typical before restart, and keep this until such time as you need to run more bulk changes.

**Comment by kotheoha** [comment] 2018-03-06 15:18
Ok, I will try that, however I want to ask the following.

If I do 3. after 2. finishes, the time I will wait for that manual checkpoint to finish will be similar to the time I am waiting now for the previously mentioned transactions? If yes, it's the same thing, I do not earn something. If transactions (derived from roll forward) depend on the last checkpoint, I think that in both cases I will wait almost the same.

If that is not the case, and the 3. step is not slow, then Ok, your recommendation matches to my wait problem. In other words, I think that when a checkpoint is not done for a long time, then when it will be done, it will be very time-expensive. Does it hold that?,

Best,
KT.

**Comment by TallTed** [comment] 2018-03-06 15:44
The transaction log, `virtuoso.trx`, holds every change action performed against the `virtuoso.db` until a `CHECKPOINT` writes those changes to the  `virtuoso.db` -- at which point the transaction log is emptied.

`virtuoso.db` is unchanged until that `CHECKPOINT` runs.  If you discard the transaction log prior to a `CHECKPOINT`, it is as if those changes were never made.

Yes, the `CHECKPOINT` will take some time.  That said, the `CHECKPOINT` will take less time than running the bulk job itself, and the `CHECKPOINT` will only happen once.

If you don't run a `CHECKPOINT`, the (still growing) transaction log will be replayed (this replay *is* the `roll forward`; there is no "derivation" happening here) at each instance launch until a `CHECKPOINT` happens.  The longer the interval (and/or the larger the changes made) between one `CHECKPOINT` and the next, the longer the next `CHECKPOINT` will take — and the longer each instance restart will take, as it must replay all transactions in the log.

**Comment by kotheoha** [comment] 2018-03-06 16:10
Ok, I see, one last question for a thing that seems confusing to me:

Since I perform various INSERT, UPDATE, DELETE sql commands to a graph G within virtuoso.db and each next command depends from the way that the previous command affected G, virtuoso.db get affected by my batch execution. The same happen as you say in virtuoso.trx.

Since, if we approximately say, that each that command corresponds to a transaction in virtuoso.trx and the G in virtuoso.db has already get affected when my batch finishes, why someone needs to make a checkpoint to transfer the content from virtuoso.trx to virtuoso.db, since the latter has already the right content?

If someone must do that, then when someone measures execution time of a long command batch in Virtuoso, then in this time must also be included the execution time of the last & unique checkpoint done when the batch finishes. This increases a lot the total execution time. Differently, if someone does not include the time of last checkpoint, the total execution time is much lower.

What is the formal way that you recommend to measure execution time in Virtuoso for long batch commands like above?

Best,
KT.

**Comment by TallTed** [comment] 2018-03-06 16:58
I think you're misunderstanding the ways Virtuoso and other database management systems work.

Users do not interact with `virtuoso.db`, as such.  At instance start, the running process combines the content of `virtuoso.db` with the content of `virtuoso.trx` (again, this is the "playback"); this ephemeral combination is what users interact with.

`virtuoso.db` is static from its initial (empty) start, until the first `CHECKPOINT`.

All changes (whether issued as SQL or SPARQL or otherwise) go into the `virtuoso.trx`, in order of `COMMIT`, until a `CHECKPOINT`.  These changes do not affect `virtuoso.db` until that `CHECKPOINT`.  At `CHECKPOINT`, the transaction log does not actually get replayed; rather, the ephemeral combination gets written to disk as `virtuoso.db`.

Following a `CHECKPOINT`, the now-changed `virtuoso.db` is again static, until the next `CHECKPOINT`.

Other DBMS use other strategies for their checkpointing.  Some DBMS do not separate the files on disk as we do; some keep *only* a transaction log which effectively plays back from zero at every launch; there are other strategies.

These differences are part of why useful DBMS benchmarking is a complex science.  DBMS comparisons *should* account for `CHECKPOINT` strategies — but they very often do not.  I suggest you read over some of the history of the [TPC](http://www.tpc.org/information/about/history.asp), the discussions of the [LDBC](http://ldbcouncil.org/), and our own blog posts on benchmarking, [starting with our series on TPC-H](https://virtuoso.openlinksw.com/blog/?id=1739).

**Comment by kotheoha** [comment] 2018-03-06 17:06
Ok, 
Thank you very much for your explanations!,
KT.

**Comment by silvae86** [comment] 2018-03-12 18:34
@TallTed can you guarantee that:

- Whenever we issue a CHECKPOINT; command to isql; 
- With the CheckpointSyncMode=2 setting in virtuoso.ini; 
- and properly wait for the response from Virtuoso,

all transactions in the .trx file are committed BEFORE the server responds?

I am seeing a case with Virtuoso 7.2.4 where i issue the CHECKPOINT; command to a docker container, the server responds and everything seems well. When the container is started up again, some triples are missing.

One **cannot** rely on a database that says it writes to the hard drive when it does not.

**Comment by TallTed** [comment] 2018-03-12 20:27
@silvae86 

At first glance, this seems like it should be a new [issue](https://github.com/openlink/virtuoso-opensource/issues/) or [question](https://stackoverflow.com/questions/tagged/virtuoso) or [support-case](http://support.openlinksw.com/support/online-support.vsp).

We would certainly be interested in more information about your described scenario.  I immediately wonder how you have determined that "some triples are missing."  Anyway -- the more detail you can provide, such that we might reproduce (and so, fix) or disprove the issue, the better!

**Comment by TallTed** [comment] 2018-03-12 20:27
@kotheoha 

Would you say that your questions have been answered, such that this issue may be closed?

**Comment by kotheoha** [comment] 2018-03-13 12:10
Hi TallTed,
yes I am covered, you can close the issue,
KT.

**Closed as completed** 2018-03-13 14:35 UTC

**Comment by debayan** [comment] 2022-01-01 09:44
Hi,
I am running a set of queries on my DB, but none of them are insert update delete queries, and yet, there is a huge transaction file being created. Any idea why?

**Comment by TallTed** [comment] 2022-01-02 05:46
@debayan -- Please delete your comment above (which is not related to this existing issue) and create a new issue here on GitHub, or post your question to the [OpenLink Community Forum](https://community.openlinksw.com/). Please include details, like the specific version of Virtuoso you're running (output of `virtuoso -?` is usually sufficient) and the name and specific version of its host OS, and an example query or two that are producing the huge transaction file. It may be helpful if you can provide the URL of your SPARQL endpoint, so we can run a few quick tests more quickly than we can tell you how to do so.

**Comment by debayan** [comment] 2022-01-02 11:00
Ok bro.
