### ISSUE TITLE
VAD File Checksum Mismatch During Installation of Conductor Package

### ISSUE THREAD

**Issue by JanKalo** [openlink/virtuoso-opensource#678] opened 2017-09-26 13:31 UTC
Hey, 

I was just setting up the newest version of Virtuoso on my Ubuntu server. 
After installation I tried to install the Conductor package, but run into a checksum mismatch.
Any idea how to solve the problem? 

````
SQL> vad_install ('/usr/local/virtuoso-opensource/share/virtuoso/vad/conductor_dav.vad', 0);
Connected to OpenLink Virtuoso
Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
15:25:12 Checkpoint started
15:25:12 Checkpoint finished, log reused
15:25:12 PL LOG: VAD_INSTALL: VAD file checksum mismatch (42VAD)
15:25:12 PL LOG: Errors were detected during installation of "/usr/local/virtuoso-opensource/share/virtuoso/vad/conductor_dav.vad".
SQL_STATE     SQL_MESSAGE
LONG VARCHAR  VARCHAR
_______________________________________________________________________________

42VAD         VAD file checksum mismatch
00000         Errors detected
00000         Installation of "/usr/local/virtuoso-opensource/share/virtuoso/vad/conductor_dav.vad" was unsuccessful.
00000         ERROR
BLOB 0 chars  

5 Rows. -- 56 msec.
```
`

**Comment by HughWilliams** [comment] 2017-09-26 17:44
What is the version of the Virtuoso server being used ? Please provide the output of running the "status('');" command and also "virtuoso-t -?" 

What is the version of the Virtuoso Conductor being used, which you can obtain with the command:

```
strings conductor_dav.vad | grep "version package"
```

**Comment by JanKalo** [comment] 2017-09-27 09:33
Version of the Virtuoso Server.
```
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.5-dev.3217-pthreads as of Sep 26 2017
Compiled for Linux (x86_64-unknown-linux-gnu)
```

Version of the Conductor Package.
`<version package="1.00.8768">`

Thanks for helping me.

**Comment by silvae86** [comment] 2017-10-02 17:41
Same problem here guys, can you please tell us the last commit where the conductor was working OK?

Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.5-dev.3217-pthreads as of Oct  2 2017
Compiled for Linux (x86_64-pc-linux-gnu)
Copyright (C) 1998-2017 OpenLink Software

Thanks!

**Comment by HughWilliams** [comment] 2017-10-02 20:37
We have been able to recreate this issue against the latest develop/7 branch and development are working on a fix for the issue ...

**Comment by silvae86** [comment] 2017-10-02 21:01
Great, thanks!

**Comment by popsovik** [comment] 2017-10-03 08:44
i just download vad file from http://opldownload.s3.amazonaws.com/uda/vad-packages/7.2/
wget http://opldownload.s3.amazonaws.com/uda/vad-packages/7.2/conductor_dav.vad
and then install it
SQL> vad_install ('/usr/local/virtuoso-opensource/share/virtuoso/vad/conductor_dav.vad.1', 0);
conductor_dav.vad.1 - filename after download :)

**Comment by HughWilliams** [comment] 2017-10-03 10:26
The problem is now fixed in the latest develop/7 branch:

```
SQL> vad_install ('../vad1/conductor_dav.vad', 0);	
SQL_STATE     SQL_MESSAGE
LONG VARCHAR  VARCHAR
_______________________________________________________________________________

00000         No errors detected
00000         Installation of "Virtuoso Conductor" is complete.
00000         Now making a final checkpoint.
00000         Final checkpoint is made.
00000         SUCCESS
BLOB 0 chars  

6 Rows. -- 4206 msec.
SQL> vad_list_packages ();
name     title    version  build_date  install_date
VARCHAR  VARCHAR  VARCHAR  VARCHAR  VARCHAR
_______________________________________________________________________________

conductor  Virtuoso Conductor  1.00.8768  2017-10-03 10:50  2017-10-03 11:24

1 Rows. -- 3 msec.
SQL> 
```

Please confirm the fix yourselves ...

**Comment by silvae86** [comment] 2017-10-03 10:37
Compiling the develop/7 branch now.

**Comment by silvae86** [comment] 2017-10-03 12:16
I can confirm the conductor is working again on the latest devel/7. Thanks!

![screen shot 2017-10-03 at 13 16 18](https://user-images.githubusercontent.com/2529555/31124602-131c403a-a83d-11e7-9cb5-3bbb19855803.png)

**Comment by HughWilliams** [comment] 2017-10-03 12:34
Good to hear, I shall close this issue now ...

**Closed as completed by HughWilliams** 2017-10-03 12:34 UTC
