### ISSUE TITLE
Possible bug with the SPARQL 1.1 Update implementation in VOS 7.1

### ISSUE THREAD

**Issue by fgiasson** [openlink/virtuoso-opensource#247] opened 2014-10-15 17:34 UTC
Hi,

I think I found a bug with the SPARQL 1.1 Update implementation in VOS 7.1.

The problem appears to be that if an object has a datatype xsd:int then it doesn't get deleted by a WITH... DELETE query.

Here are the sparql queries you can use in iSQL that will replicate the issue:

```
sparql clear graph <http://test.com/tests/>;

sparql
insert data 
{
  graph <http://test.com/tests/> {
    <http://foo.com/datasets/tests/foo> <http://purl.org/ontology/wsf#product_in_inventory> "9"^^<http://www.w3.org/2001/XMLSchema#int> .
  }
};

sparql
select *
from <http://test.com/tests/>
where
{
  ?s ?p ?o .
};

sparql
with <http://test.com/tests/>
delete 
{ 
  <http://foo.com/datasets/tests/foo> <http://purl.org/ontology/wsf#product_in_inventory> ?o .
}
where
{
  <http://foo.com/datasets/tests/foo> <http://purl.org/ontology/wsf#product_in_inventory> ?o .
};

sparql
select *
from <http://test.com/tests/>
where
{
  ?s ?p ?o .
};
```

As you can see, the triple is still there when we run the last SPARQL query. If we don't mention any datatype (or if you mention xsd:string, or xsd:dateTime, or whatever) it gets deleted:

```
sparql clear graph <http://test.com/tests/>;

sparql
insert data 
{
  graph <http://test.com/tests/> {
    <http://foo.com/datasets/tests/foo> <http://purl.org/ontology/wsf#product_in_inventory> "9" .
  }
};

sparql
select *
from <http://test.com/tests/>
where
{
  ?s ?p ?o .
};

sparql
with <http://test.com/tests/>
delete 
{ 
  <http://foo.com/datasets/tests/foo> <http://purl.org/ontology/wsf#product_in_inventory> ?o .
}
where
{
  <http://foo.com/datasets/tests/foo> <http://purl.org/ontology/wsf#product_in_inventory> ?o .
};

sparql
select *
from <http://test.com/tests/>
where
{
  ?s ?p ?o .
};
```

Question one: if there a work around that would work the same way but with another syntax that doesn't trigger the bug?

Also note that the same query (but using delete from) SPARQL query was working as expected with VOS 6.x.

Thanks

Fred

**Comment by rumito** [comment] 2014-10-16 06:50
Hi Fred,

Thank you for reporting this, I have been able to reproduce and notified the development ..

Best Regards,
Rumi Kocis

**Comment by fgiasson** [comment] 2014-10-16 12:03
Hi Rumi!

Not sure if it is Ivan that will fix this issue, but please ask the developer to see if he could come up with a workaround if this cannot be fixed in near time. I tried a few options without any luck so far.

Thanks,

Fred

**Comment by fgiasson** [comment] 2014-10-22 12:24
Any updates with this issue? I was wondering if there was a possibility to have a ETA for the resolution. It is currently blocking the release of the Open Semantic Framework which would use th Virtuoso 7.1 (currently 6.1.8 :|)

Thanks

**Comment by olivierdalang** [comment] 2014-12-10 08:54
I'm not sure it's the same issue, but there's this thread too where I can't delete typed triples neither
http://sourceforge.net/p/virtuoso/mailman/message/32959120/

I'd love an ETA too since I'm stuck too because of this issue...

This works (creates and then delete the triple) :

```
INSERT INTO GRAPH <http://mygraph/> {
  <http://mygraph/#myitem> <http://www.w3.org/2000/01/rdf-schema#label> "Blabla" .
}

DELETE FROM GRAPH <http://mygraph/> {
    <http://mygraph/#myitem > <http://www.w3.org/2000/01/rdf-schema#label> "Blabla" .
}
```

But this doesn't work (the triple is created, but not deleted, with no
error) :

```
INSERT INTO GRAPH <http://mygraph/> {
    <http://mygraph/#austrian_lot_source_1> <http://www.opengis.net/ont/geosparql#geometry> "MULTIPOLYGON(((0.0 0.0,1.0 0.0,1.0 1.0,0.0 1.0,0.0 0.0)))"^^<http://www.openlinksw.com/schemas/virtrdf#Geometry> .
}

DELETE FROM GRAPH <http://mygraph/> {
    <http://mygraph/#austrian_lot_source_1> <http://www.opengis.net/ont/geosparql#geometry> "MULTIPOLYGON(((0.0 0.0,1.0 0.0,1.0 1.0,0.0 1.0,0.0 0.0)))"^^<http://www.openlinksw.com/schemas/virtrdf#Geometry> .
}
```

**Comment by HughWilliams** [comment] 2014-12-10 16:17
Oliver, Your case seems more geospatial related and an internal report has already been created for this for the post you made on the mailing list a few weeks ago and it still to be looked into by development ...

**Comment by IvanMikhailov** [comment] 2014-12-10 21:45
Oliver,
I'm testing the fix ATM, hope it's in production quite soon.

**Comment by fgiasson** [comment] 2014-12-10 22:03
@IvanMikhailov that specific issue, or the geo related one outlined by Olivier? (or they are the same?)

**Comment by fgiasson** [comment] 2014-12-19 20:36
Could this be related to: #131 and/or #146?

**Comment by fgiasson** [comment] 2014-12-22 20:29
I just encountered this issue another time... that time, it is with a xsd:string:

```
<binding name="o"><literal>#F9B571</literal></binding>Virtuoso 22023 Error SR544: Function __xsd_type() can not find XML Schema datatype that matches SQL datatype UNAME (217)
```

If I check what is output in HTML, I can see that the literal is supposed to be xsd:string, but with any other mime, I get that error... So it doesn't seem to be related to specific XSD types.

Any ideas? This is becoming a real problem...

**Comment by kidehen** [comment] 2014-12-22 21:00
On 12/22/14 3:30 PM, Frederick Giasson wrote:

> I just encountered this issue another time... that time, it is with a 
> xsd:string:
> 
> |<binding name="o"><literal>#F9B571</literal></binding>Virtuoso 22023 Error SR544: Function __xsd_type() can not find XML Schema datatype that matches SQL datatype UNAME (217)
> |
> 
> If I check what is output in HTML, I can see that the literal is 
> supposed to be xsd:string, but with any other mime, I get that 
> error... So it doesn't seem to be related to specific XSD types.
> 
> Any ideas? This is becoming a real problem...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/openlink/virtuoso-opensource/issues/247#issuecomment-67885771.

This has been fixed. Only issue is rollout ETA.

I've pinged the development team re. ETA confirmation.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment] 2014-12-22 21:06
Hi @kidehen,

Wonderful thanks!

When you say rollout, you mean the commit in this repository (the dev/7 branch)?

Thanks

**Comment by kidehen** [comment] 2014-12-22 21:24
On 12/22/14 4:06 PM, Frederick Giasson wrote:

> Hi @kidehen https://github.com/kidehen,
> 
> Wonderful thanks!
> 
> When you say rollout, you mean the commit in this repository?

Yes.

## 

Regards,

Kingsley Idehen 
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by fgiasson** [comment] 2014-12-23 19:34
It appears that a commit has been commited for this issue: 26e7a6a10d39250094e0521dd127e6a5e196ae81

If this is the case, does it also fix these other issues issues: #131 & #146?

**Comment by HughWilliams** [comment] 2014-12-23 19:48
@fgiasson:  Yes, that is suppose to be the fix for this issue, but it only resolves the issue reported by @olivierdalang in this git issue  and not your original from my testing, thus @IvanMikhailov needs to look into this again ...

**Comment by fgiasson** [comment] 2014-12-23 22:16
@HughWilliams, @IvanMikhailov: ok good thanks.

I think that a more pressing issues are #131 and #146 since I am experimenting a log of issues incurring datatype() in both the `select` statement or a `bind` statement like (with or without the subquery):

```
select ?s ?o ?otype
from <http://foo.com/dataset/>
where
{
  ?s <http://purl.org/ontology/sco#color> ?o
  bind (datatype(?o) as ?otype)
}
```

```
select ?s ?p ?o (DATATYPE(?o)) as ?otype (LANG(?o)) as ?olang
where
{
  {
    select distinct ?s from <http://foo.com/dataset>
    where
    {
      ?s a ?type.
    }
    limit 50
    offset 0
  }

  ?s ?p ?o
}
```

etc. No specific datatypes appears to be the problem, but different xsd types appears to be leading to the `"Virtuoso 22023 Error SR544: Function __xsd_type() can not find XML Schema datatype that matches SQL datatype UNAME (217)"` error.

**Comment by HughWilliams** [comment] 2014-12-24 03:22
@fgiasson: the issue reported in #131 and #146 has not been resolved yet .. have requested and update on when this can be expected to be fixed ...

**Comment by fgiasson** [comment] 2014-12-29 14:46
@HughWilliams great thanks! In mean time, could you think of a wordaround for ending up with the same results as provided by this query?

```
select ?s ?p ?o (DATATYPE(?o)) as ?otype (LANG(?o)) as ?olang
where
{
  {
    select distinct ?s from <http://foo.com/dataset>
    where
    {
      ?s a ?type.
    }
    limit 50
    offset 0
  }
  ?s ?p ?o
}
```

Since right now, as far as I can see, I cannot get back any datatypes from the triple store and this is blocking the normal operations of the Open Semantic Framework 3.1 (previous versions works since they are using Virtuoso 6.1.8).

**Comment by HughWilliams** [comment] 2015-01-08 14:41
@fgiasson : Your issue has now been resolved in the latest  git develop/7 update:

SQL> sparql clear graph http://test.com/tests/;

Done. -- 0 msec.
SQL> sparql select \* from http://test.com/tests/ where {   ?s ?p ?o . };
s                                                                                 p                                                                                 o
VARCHAR                                                                           VARCHAR                                                                           VARCHAR

---

0 Rows. -- 0 msec.
SQL> sparql insert data  {   graph http://test.com/tests/ {     http://foo.com/datasets/tests/foo http://purl.org/ontology/wsf#product_in_inventory "9"^^http://www.w3.org/2001/XMLSchema#int .   } };

Done. -- 0 msec.
SQL> sparql select \* from http://test.com/tests/ where {   ?s ?p ?o . };
s                                                                                 p                                                                                 o
VARCHAR                                                                           VARCHAR                                                                           VARCHAR

---

http://foo.com/datasets/tests/foo                                                 http://purl.org/ontology/wsf#product_in_inventory                                 9

1 Rows. -- 0 msec.
SQL> sparql with http://test.com/tests/ delete  {    http://foo.com/datasets/tests/foo http://purl.org/ontology/wsf#product_in_inventory ?o . } where {   http://foo.com/datasets/tests/foo http://purl.org/ontology/wsf#product_in_inventory ?o . };

Done. -- 1 msec.
SQL> sparql select \* from http://test.com/tests/ where {   ?s ?p ?o . };
s                                                                                 p                                                                                 o
VARCHAR                                                                           VARCHAR                                                                           VARCHAR

---

0 Rows. -- 0 msec.
SQL> status('');
REPORT
VARCHAR

---

OpenLink Virtuoso  Server
Version 07.10.3211-pthreads for Linux as of Jan  8 2015 
Started on: 2015-01-08 15:25 GMT+1

See: http://sourceforge.net/p/virtuoso/virtuoso-opensource/ci/a170a0f4ba63acbaf403ac83964d58a815fb2241/

**Closed as completed by HughWilliams** 2015-01-08 14:41 UTC

**Comment by fgiasson** [comment] 2015-01-08 15:01
Hi @HughWilliams!

Fantastic, thanks! Does this fix also impact #146 ?

**Comment by HughWilliams** [comment] 2015-01-08 15:29
@fgiasson: No , issues #146 & #131 are still to be resolved ...

**Comment by fgiasson** [comment] 2015-01-08 15:29
@HughWilliams good thanks for confirming.

**Comment by IvanMikhailov** [comment] 2015-01-11 17:26
Oliver,
The bug is fixed, the fix is on its way to production.

**Comment by fgiasson** [comment] 2015-01-15 21:10
@IvanMikhailov , @HughWilliams ,

Does this fix #131  and #146  as well?

**Comment by HughWilliams** [comment] 2015-01-15 21:44
@fgiasson: Yes , the fix for the "SR544: Function __xsd_type() can not find XML Schema datatype that matches SQL datatype UNAME (217)" error has been committed to develop/7 branch ...

**Comment by fgiasson** [comment] 2015-01-15 21:45
Fantastic thanks for confirming!

**Comment by fgiasson** [comment] 2015-01-23 16:52
I confirm that the issue I was experiencing is fixed with the latest code, thanks!
