### ISSUE TITLE
Persistent namespaces not so persistent

### ISSUE THREAD

**Issue by silvae86** [openlink/virtuoso-opensource#737] opened 2018-05-03 20:23 UTC
Hello,

I am seeing errors both in the develop/7 release and also at the latest commit, showing that although namespaces are present in the virtuoso conductor, they are not found when running SPARQL queries. 

## To replicate

I have built a dockerfile based on the tenforce/virtuoso dockerfile for deploying an application. 

Please run it as such:

````bash
#start container
docker run  -p 8890:8890 \
            -p 1111:1111 \
            --name virtuoso-dendro \
            -d joaorosilva/virtuoso:7.2.4-for-dendro-0.3
````

Access the conductor at 127.0.0.1:8890, login with default credentials: dba + dba

Go to the Persistent Namespaces tab, check that **there is a namespace called 'ddr'**. 

Now run this query in the Conductor:

````sparql
SPARQL
WITH <http://127.0.0.1:3002/dendro_graph>
ASK 
WHERE 
{ 
   {
       <http://dendro.fe.up.pt/ontology/research/> ?p ?o. 
<http://dendro.fe.up.pt/ontology/research/> rdf:type ddr:Resource   }
} 
````

You will see this error:

````
Line 10: SP030: SPARQL compiler, line 8: Undefined namespace prefix at 'ddr' before '}'
````

However, if you go to the Persistent Namespaces, delete the 'ddr' namespace and recreate it again using the conductor's web interface and with the same uri, "http://dendro.fe.up.pt/ontology/0.1/", the query runs flawlessly and returns false.

I am declaring the namespaces in a script as such:

````sparql
DB.DBA.XML_REMOVE_NS_BY_PREFIX('ddr', 2);
DB.DBA.XML_SET_NS_DECL ('ddr', 'http://dendro.fe.up.pt/ontology/0.1/', 2);
````

I am at a loss here. How can I declare namespaces in a reliable way? Nothing works without them...

Thanks for the attention!

**Comment by silvae86** [comment] 2018-05-08 12:25
I think i figured it out. Before shutting down the docker container you need to issue a checkpoint; command, as such:

````bash
docker exec virtuoso-dendro /bin/bash -c "sync && /usr/local/virtuoso-opensource/bin/isql-v 1111 -U dba -P dba 'EXEC=checkpoint;'"
````

Otherwise, it seems like some of the data is cached and will not be persisted to the hard drive. Quite a caveat!

**Comment by HughWilliams** [comment] 2018-05-08 13:42
I am not able to recreate this issue against the VOS `develop/7` branch --

```
De-iMac-554:database hwilliams$ ~/src/git/vos-7-develop/binsrc/virtuoso/virtuoso-t
De-iMac-554:database hwilliams$ ~/Downloads/isql 1111
Connected to OpenLink Virtuoso
Driver: 07.20.3217 OpenLink Virtuoso ODBC Driver
OpenLink Interactive SQL (Virtuoso), version 0.9849b.
Type HELP; for help and EXIT; to exit.
SQL> DB.DBA.XML_REMOVE_NS_BY_PREFIX('ddr', 2);

Done. -- 2 msec.
SQL> DB.DBA.XML_SET_NS_DECL ('ddr', 'http://dendro.fe.up.pt/ontology/0.1/', 2);

Done. -- 1 msec.
SQL> shutdown;
De-iMac-554:database hwilliams$ ~/src/git/vos-7-develop/binsrc/virtuoso/virtuoso-t
De-iMac-554:database hwilliams$ ~/Downloads/isql 1111
Connected to OpenLink Virtuoso
Driver: 07.20.3214 OpenLink Virtuoso ODBC Driver
OpenLink Interactive SQL (Virtuoso), version 0.9849b.
Type HELP; for help and EXIT; to exit.
SQL> sparql select * where {ddr:whatever ?p ?o};
p                                                                                 o
LONG VARCHAR                                                                      LONG VARCHAR
_______________________________________________________________________________


0 Rows. -- 3 msec.
SQL> status('');
REPORT
VARCHAR
_______________________________________________________________________________

OpenLink Virtuoso  Server
Version 07.20.3217-pthreads for Darwin as of Feb  6 2018 
Started on: 2018-05-08 14:27 GMT+1
```

-- which is what I would expect as setting the 3rd `bit` param in the `DB.DBA.XML_SET_NS_DECL ()` function to `2` persists the param to a system table as detailed at --

     http://docs.openlinksw.com/virtuoso/fn_xml_set_ns_decl/

-- and I can't see the use of docker having anything to do with it ...

The only reason I can see for such an error occurring is if for some reason you have turned database transaction logging off, such that transactions are not be written to the `virtuoso.trx` transaction log file, in which case they are held in memory only and an explicit checkpoint has to be performed to commit them to the physical database, i.e., `virtuoso.db` file.

Transaction logging is on by default and typically changed or turned off with the `log_enable()` function:

    http://docs.openlinksw.com/virtuoso/fn_log_enable/

**Comment by IS4Code** [comment] 2023-12-06 19:27
I can confirm, shutting down the server via `kill` caused this issue. Running `checkpoint;` and `shutdown;` in the interactive SQL console fixed it after restarting.

**Comment by TallTed** [comment] 2023-12-06 21:29
Shutting down the server via `kill` is little different from powering down the physical host, and [as noted above](https://github.com/openlink/virtuoso-opensource/issues/737#issuecomment-387406437) by @HughWilliams, a Virtuoso instance running with default configuration (`log_enable (1);`) will have a transaction log (`.trx`) file that plays back upon the next launch, such that persistent namespaces — as well as any other changes to the DB — will persist.

Instances running without transaction logging (e.g., with `log_enable (0);`) — against our recommendation! — will indeed lose any changes that have been made since the last [`CHECKPOINT`](https://docs.openlinksw.com/virtuoso/checkpoint/#checkpoint)ed (which is built into the [`SHUTDOWN`](https://docs.openlinksw.com/virtuoso/checkpoint/#checkpoint) procedure).

As this is expected behavior, I'll close this issue with this comment.

**Closed as completed by TallTed** 2023-12-06 21:29 UTC
