### ISSUE TITLE
problem with version

### ISSUE THREAD

**Issue by galexiou** [openlink/virtuoso-opensource#8] opened 2012-07-23 10:58 UTC
Hi,
I have installed virtuoso version 6.1.5 and from the terminal when i type virtuoso-t -? i get Version 6.1.5.3127-pthreads as of Jul 18 2012  but from my conductor i see that i have Version: 06.01.3127. When i try to install certain vad packages such as rdfb2rdf_vad i get a message that tells me to upgrade my version.

**Comment by openlink** [comment] 2012-07-23 14:24
Virtuoso uses the major and minor numbers of the release (in this case 06.01) combined with the engine number (3127) in the VAD sticker, to make sure the package can only be installed on virtuoso executables of a certain level. 

At this time VOS does not yet have a rdb2rdf_dav.vad package, so i am assuming you are using a package you downloaded that was made for the commercial product. 

We are working to add this functionality to the VOS tree shortly.

**Comment by galexiou** [comment] 2012-07-23 17:14
So there is no problem at all with this inconsistency in versioning and the only way to know which version i have is by typing "virtuoso-t -?" ? Is this  normal or i have to do something to fix it?

**Comment by openlink** [comment] 2012-07-24 09:36
Yes:

virtuoso-t -? shows the major.minor.revision + engine number

some other places like the conductor only show major.minor + engine.

So using virtuoso-t -? shows you the most complete version information, but internally for VAD packages we do not check the revision, since the changes it relies on are mostly encoded into the engine version.

**Comment by openlink** [comment] 2012-07-24 09:37
BTW i can confirm the rdb2rdf_dav.vad will be part of the upcoming 6.1.6 version of VOS

**Closed as completed by openlink** 2012-07-24 09:36 UTC

**Comment by galexiou** [comment] 2012-07-24 09:44
Ok got it!! thank you very much for your information and nice to hear abt the rdb2rdf ability! Btw we have some other problems which are described in this post [ http://boards.openlinksw.com/phpBB3/viewtopic.php?f=12&t=2960 ] but we cannot obtain a useful and clear  answer! Could you check it please?
