### ISSUE TITLE
Bulk load hangs on V7

### ISSUE THREAD

**Issue by ghirardinicola** [openlink/virtuoso-opensource#75] opened 2013-08-01 12:26 UTC
Trying to load this freebase cleaned dataset:
https://github.com/paulhoule/infovore/wiki/:BaseKB%20Lime
http://basekb.com/docs/virtuoso.php

At the beginning all the cpu are under heavy load but after a while only one goes to 100% and disk activity stop.
If I force stop and restart "Roll forward" runs.

**Comment by openlink** [comment] 2013-08-01 12:52
Can you give me some information on the machine you are using to load this dataset, particularly the CPU type, number of cores and the amount of memory in the system.

Also i would like to know the value of the NumberOfBuffers setting from your virtuoso.ini in the [Parameters] section.

**Comment by ghirardinicola** [comment] 2013-08-01 13:03
4 cpu, 8 cores , at the end the details.
16 gb ram, used only 2 gb during bulk load.
NumberOfBuffers          = 680000
  MaxDirtyBuffers          = 500000
MaxCheckpointRemap = 200000

virtuoso compiled on "Debian GNU/Linux 7.1"
branch develop/7 onw week ago approx (stated as rc2 during install if i remember well)

Thanks for the help!

cpu details (four like this):

processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 44
model name  : Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
stepping    : 2
microcode   : 0x15
cpu MHz     : 2394.000
cache size  : 12288 KB
physical id : 0
siblings    : 2
core id     : 0
cpu cores   : 2
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 11
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes hypervisor lahf_lm ida arat dtherm
bogomips    : 4788.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

complete virtuoso.ini

;
;  virtuoso.ini
;
;  Configuration file for the OpenLink Virtuoso VDBMS Server
;
;  To learn more about this product, or any other product in our
;  portfolio, please check out our web site at:
;
;      http://virtuoso.openlinksw.com/
;
;  or contact us at:
;
;      general.information@openlinksw.com
;
;  If you have any technical questions, please contact our support
;  staff at:
;
;      technical.support@openlinksw.com
;
;
;  Database setup
;
[Database]
DatabaseFile       = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.db
ErrorLogFile       = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.log
LockFile           = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.lck
TransactionFile    = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.trx
xa_persistent_file = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.pxa
ErrorLogLevel      = 7
FileExtend         = 200
MaxCheckpointRemap = 200000
Striping           = 0
TempStorage        = TempDatabase

[TempDatabase]
DatabaseFile       = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso-temp.db
TransactionFile    = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuoso-temp.trx
MaxCheckpointRemap = 2000
Striping           = 0

[Parameters]
ServerPort               = 1111
LiteMode                 = 0
DisableUnixSocket        = 1
DisableTcpSocket         = 0
;SSLServerPort                  = 2111
;SSLCertificate                 = cert.pem
;SSLPrivateKey                  = pk.pem
;X509ClientVerify               = 0
;X509ClientVerifyDepth          = 0
;X509ClientVerifyCAFile         = ca.pem
ServerThreads            = 20
CheckpointInterval       = 60
O_DIRECT                 = 0
CaseMode                 = 2
MaxStaticCursorRows      = 5000
CheckpointAuditTrail     = 0
AllowOSCalls             = 0
SchedulerInterval        = 10
DirsAllowed              = ., /usr/local/virtuoso-opensource/share/virtuoso/vad, /production/datasets
ThreadCleanupInterval    = 0
ThreadThreshold          = 10
ResourcesCleanupInterval = 0
FreeTextBatchSize        = 100000
SingleCPU                = 0
VADInstallDir            = /usr/local/virtuoso-opensource/share/virtuoso/vad/
PrefixResultNames        = 0
RdfFreeTextRulesSize     = 100
IndexTreeMaps            = 256
MaxMemPoolSize           = 200000000
PrefixResultNames        = 0
MacSpotlight             = 0
IndexTreeMaps            = 64

NumberOfBuffers          = 680000
  MaxDirtyBuffers          = 500000

[HTTPServer]
ServerPort                  = 8890
ServerRoot                  = /usr/local/virtuoso-opensource/var/lib/virtuoso/vsp
ServerThreads               = 20
DavRoot                     = DAV
EnabledDavVSP               = 0
HTTPProxyEnabled            = 0
TempASPXDir                 = 0
DefaultMailServer           = localhost:25
ServerThreads               = 10
MaxKeepAlives               = 10
KeepAliveTimeout            = 10
MaxCachedProxyConnections   = 10
ProxyConnectionCacheTimeout = 15
HTTPThreadSize              = 280000
HttpPrintWarningsInOutput   = 0
Charset                     = UTF-8
HTTPLogFile                 = /usr/local/virtuoso-opensource/var/lib/virtuoso/db/virtuosoHttp01082013.log

[AutoRepair]
BadParentLinks = 0

[Client]
SQL_PREFETCH_ROWS  = 100
SQL_PREFETCH_BYTES = 16000
SQL_QUERY_TIMEOUT  = 0
SQL_TXN_TIMEOUT    = 0
;SQL_NO_CHAR_C_ESCAPE           = 1
;SQL_UTF8_EXECS                 = 0
;SQL_NO_SYSTEM_TABLES           = 0
;SQL_BINARY_TIMESTAMP           = 1
;SQL_ENCRYPTION_ON_PASSWORD     = -1

[VDB]
ArrayOptimization           = 0
NumArrayParameters          = 10
VDBDisconnectTimeout        = 1000
KeepConnectionOnFixedThread = 0

[Replication]
ServerName   = db-GICLAB07
ServerEnable = 1
QueueMax     = 50000

[Striping]
Segment1 = 100M, db-seg1-1.db, db-seg1-2.db
Segment2 = 100M, db-seg2-1.db
;...
;[TempStriping]
;Segment1                       = 100M, db-seg1-1.db, db-seg1-2.db
;Segment2                       = 100M, db-seg2-1.db
;...
;[Ucms]
;UcmPath                        = <path>
;Ucm1                           = <file>
;Ucm2                           = <file>
;...

[Zero Config]
ServerName = virtuoso (GICLAB07)
;ServerDSN                      = ZDSN
;SSLServerName                  =
;SSLServerDSN                   =

[Mono]
;MONO_TRACE                     = Off
;MONO_PATH                      = <path_here>
;MONO_ROOT                      = <path_here>
;MONO_CFG_DIR                   = <path_here>
;virtclr.dll                    =

[URIQA]

DynamicLocal = 0
DefaultHost  = 130.186.102.3:8890

[SPARQL]
;ExternalQuerySource            = 1
;ExternalXsltSource             = 1
;DefaultGraph                   = http://localhost:8890/dataspace
;ImmutableGraphs                = http://localhost:8890/dataspace
ResultSetMaxRows           = 10000
MaxQueryCostEstimationTime = 400        ; in seconds
MaxQueryExecutionTime      = 60 ; in seconds
DefaultQuery               = select distinct ?Concept where {[] a ?Concept} LIMIT 100
DeferInferenceRulesInit    = 0  ; controls inference rules loading
;PingService                    = http://rpc.pingthesemanticweb.com/

[Plugins]
LoadPath = /usr/local/virtuoso-opensource/lib/virtuoso/hosting
;Load1                          = plain, wikiv
;Load2                          = plain, mediawiki
;Load3                          = plain, creolewiki
;Load4                  = plain, im
;Load5          = plain, wbxml2
;Load6                  = plain, hslookup
;Load7                  = attach, libphp5.so
;Load8                  = Hosting, hosting_php.so
;Load9                  = Hosting,hosting_perl.so
;Load10         = Hosting,hosting_python.so
;Load11         = Hosting,hosting_ruby.so
;Load12                         = msdtc,msdtc_sample

**Comment by indeyets** [comment] 2013-08-01 13:14
@ghirardinicola please check IO load (using `iostat` or any tool you like) — I believe you would see full hdd utilization there.

So, to load this dataset you will need to increase buffers and virtuoso will work ok occupying more ram. Until some point where you will exhaust the buffers again and your only option would be to add even more ram to the system.

**Comment by ghirardinicola** [comment] 2013-08-01 13:48
I changed the buffers level but the ram usage stay at 1,3 gb.
       NumberOfBuffers          = 1360000
       MaxDirtyBuffers          = 1000000

The load is split in 1024 files, i don't think it is a problem of big load.
How I can debug what happens when it stops to load?

**Comment by ghirardinicola** [comment] 2013-08-02 08:31
Discovered the trick:
spaces before lines in virtuoso.ini make the parameter being ignored
(without any warning!!!)

I'm not the only one:
http://stackoverflow.com/questions/11946022/loading-rdf-triples-into-virtuoso-opensource

I'll let you know if the bulk load hanging problem is solved with more RAM
used, but I don't think so.

**Comment by jakubklimek** [comment] 2013-08-02 14:09
Hi, isn't this issue a duplicate of https://github.com/openlink/virtuoso-opensource/issues/40? At least, it is related.

**Closed as completed** 2014-02-19 11:49 UTC
