### ISSUE TITLE
Dereferencing URIs with Greek Characters in Faceted Browser 

### ISSUE THREAD

**Issue by galexiou** [openlink/virtuoso-opensource#12] opened 2012-08-07 13:59 UTC
We're having a problem with URIs that contain greek characters. It seems that Virtuoso messes up the encoding in a way that when using /describe/?uri={someURI} the query uses a scrambled version of the original URI that does not correspond to any actual resource.
Is there any workaround, maybe by tweaking the code in description.vsp/description.sql?
Some additional information: In virtuoso.ini the character encoding is "utf-8" and we have set "set http_charset='UTF-8' ;" in description.vsp.

**Comment by galexiou** [comment] 2012-08-08 10:34
any ideas?

**Comment by openlink** [comment] 2012-08-08 11:46
I am working on a fix for this. Will let you know as soon as the patch has been committed.

**Comment by galexiou** [comment] 2012-08-08 11:58
do you have an ETA? It's crucial for us...please let me know!!!

Thanks in advance!!!!

**Comment by ioanag** [comment] 2012-08-08 22:04
the above comment posted by galexiou is too crucial for our team as well. We tried virtually anything towards a potential solution. We are looking forward for the patch...!!!

**Comment by openlink** [comment] 2012-08-09 22:20
galexiou: Do you have a sample URL so i see the exact problem you have. I have a partial fix already, but i wish to make sure i fix all the fields/links that cause problems.

**Comment by galexiou** [comment] 2012-08-10 10:27
yes this is a test uri http://publicspending.medialab.ntua.gr/describe/?url=http://publicspending.medialab.ntua.gr/resource/decisions/ΒΟΖ24691ΩΓ-Τ2Β  that i made for you! Please let me knwo as soon as you try!!!! if you type it directly from the browser you don't seem to have any problems in dereferencing but if you try to follow a link from description.vsp then problems start.  Follow the link ( d:refersTo ) for example from that uri! 

Thanks in advance for your help!!!

**Comment by openlink** [comment] 2012-08-10 14:37
galexiou: i just tried your examine and i can see what is going on. I will go over the code and continue working on a patch. It should be ready on Monday.

**Comment by galexiou** [comment] 2012-08-13 12:09
any good news?

**Comment by galexiou** [comment] 2012-08-22 10:39
Hello again..and excuse me for reposting, but i have no news from you yet!! Is the patch ready? Do you have any updates?
Thanks a lot in advance!

**Comment by openlink** [comment] 2012-08-22 12:56
I just uploaded a set of fixes to the develop/6 branch of this project.

Note you need to build BOTH a new virtuoso binary AND install the latest fct_dav.vad package in your database.

Please test and let me know if this resolves all of your problems.

**Comment by galexiou** [comment] 2012-08-22 13:55
So i should upgrade to 6.1.6/stable release to be sure  and patch description.vsp with the new one you provided in develop/6 branch?

**Comment by openlink** [comment] 2012-08-22 22:10
We made some patches for the server binary as well as several patches for the facet browser package, so the easiest is to build both binary + vad from develop/6 branch.

**Comment by openlink** [comment] 2012-08-29 09:31
Can you confirm the patches in develop/6 resolve your problem please?

**Comment by galexiou** [comment] 2012-09-07 10:24
Hello again, I made a setup of 6/develop branch ( 6.1.7.) to test the patches for dereferencing and for this purpose i uploaded a subgraph of our main graph. The problem seems to have a partial fix and you can test it on your own at the following address :  http://83.212.100.127:8890/describe/?uri=publicspending.medialab.ntua.gr/resource/decisions/%CE%924%CE%98%CE%9F4691%CE%9F8-3%CE%9A%CE%94 ( please notice that that first time seems to be ok but if you go to metadata menu and then back to description menu it scrambles the encoding also i go make a mouseover at the third value seems to be ok but the fourth value is scrambled ) any ideas?

**Comment by galexiou** [comment] 2012-09-13 13:08
any feedback?

**Comment by galexiou** [comment] 2012-10-26 01:39
Hello...We still experience the problem!!! Any Feedback yet?

**Comment by jakubklimek** [comment] 2013-01-05 14:21
Hi, we experience the same problem using Czech characters in URI. When can we expect a final fix?

**Comment by imitko** [comment] 2013-02-14 13:28
The issue have been fixed, should pull the recent sources from github and build new vad from binsrc/b3s directory.
On local installation test with : http://localhost:8890/describe/?url=http%3A%2F%2Fel.dbpedia.org%2Fresource%2FΦαίακες&lang=el

**Comment by galexiou** [comment] 2013-02-14 23:44
I'm afraid that the issue has not been fixed..i just installed, again, the virtuoso from the new sources but when i try to test it, it dereferences only the  "About: " section correct and when i try to click other links it justs scrambles the characters... here is the proof: http://83.212.110.193:8890/fct/rdfdesc/description.vsp?g=publicspending.medialab.ntua.gr/resource/payments/4%CE%91%CE%93%CE%9246904%CE%A3-%CE%A8

Please try and tell me your opinion.

Waiting for your answer.

P.S. this link will be for a limited time up, so please try it as soon as possible...thank you.

**Comment by imitko** [comment] 2013-02-15 08:44
I see the problem, working on a fix

**Comment by imitko** [comment] 2013-02-15 10:31
fix is done. please take the latest changes from github in develop/6 branch.

**Comment by galexiou** [comment] 2013-02-15 15:13
Ok i think issue can close now. Thank you very much for the fix you can check the proof at the above link. May i ask what the problem was?

Thank you again.
Giorgos

**Comment by imitko** [comment] 2013-02-15 15:18
The problem was printing UTF-8 string using narrow pattern %U, the URL plain string must be converted to NVARCHAR before to print in order to get proper URL escape.

**Closed as completed by imitko** 2013-02-15 15:18 UTC

**Comment by jakubklimek** [comment] 2013-02-18 11:14
Hi there,

I just downloaded the fixed version (today, 18.2.2013), but again, it is only partly fixed.

Take a look here: http://xrg13.projekty.ms.mff.cuni.cz:8890/describe/?url=http%3A%2F%2Flinked.opendata.cz%2Fresource%2Fcourt%2Fcz%2F%C3%BAstavn%C3%AD-soud&sid=1

It is czech data, not greek but I guess the problem is the same.

Now if I click on property value, which contains unicode in URI, it works OK.

But, if I click on the „About:“ link or click on metadata and back on description, it is bad again.

Thanks for the progress though,

Jakub Klímek

**Comment by imitko** [comment] 2013-02-20 11:35
Please take the new revision of the FCT, also make sure you are using recent server binary from develop/6 branch.

wkr,
Mitko

**Comment by jakubklimek** [comment] 2013-02-27 15:11
OK, updated today, fct v. 1.13.11. The bug mentioned above is fixed, thank you. However, I have found the problem again elsewhere. In the full text search when I find URIs with UTF8 characters, the links to them still contain the bug.

Steps:
in Precision Search & Find, find URIs with UTF-8 characters in them
Observe the found URI links and try to click them
