### ISSUE TITLE
STR() applied to numbers provided via VALUES produces true

### ISSUE THREAD

**Issue by jindrichmynarz** [openlink/virtuoso-opensource#539] opened 2016-03-02 15:50 UTC
When you apply [`STR()`](https://www.w3.org/TR/sparql11-query/#func-str) to more than one number provided via [`VALUES`](https://www.w3.org/TR/sparql11-query/#inline-data) Virtuoso outputs `true` instead of the number as a string. For example, the following query produces 2 `true` bindings:

``` sparql
SELECT (STR(?n) AS ?nStr)
WHERE {
  VALUES ?n {
    1
    2
  }
}
```

Interestingly, when only a single number is provided in `VALUES`, Virtuoso stringifies it correctly:

``` sparql
SELECT (STR(?n) AS ?nStr)
WHERE {
  VALUES ?n {
    1
  }
}
```

The expected behaviour is that Virtuoso produces stringified numbers instead of `true` even for multiple bindings provided via `VALUES`.

Tested on Virtuoso 07.20.3215.

**Comment by IvanMikhailov** [comment] 2016-03-02 21:57
Jindřich,

Sorry, that's my fault. For some reason SPARQL optimizer decides that if ?n can be used as boolean without a cast then it can be treated as boolean when it's passed to non-boolean STR(). For a single-row VALUES the optimizer treats ?n as a constant value so the constant is used instead of variable.

**Comment by jindrichmynarz** [comment] 2016-03-02 22:25
I don't know if I understand you correctly. I can imagine that `1` can be used as boolean `true`, but other numbers are casted to `true` as well.

**Comment by IvanMikhailov** [comment] 2016-03-02 22:33
Yes, the problem is the invalid cast. Even 1 is not a "boolean" in this context because it is not typed as xsd:boolean .

**Comment by IvanMikhailov** [comment] 2016-03-03 04:34
For all recent versions, the fix is

``` c
diff --git a/libsrc/Wi/sparql2sql.c b/libsrc/Wi/sparql2sql.c
index ce25e67..4d892ab 100644
--- a/libsrc/Wi/sparql2sql.c
+++ b/libsrc/Wi/sparql2sql.c
@@ -4339,7 +4339,11 @@ spar_refresh_binv_var_rvrs (sparp_t *sparp, SPART *binv)
                 if (restr_set & SPART_VARR_LONG_EQ_SQL)
                   {
                     if (DV_ARRAY_OF_POINTER == datum_dtp)
-                      datum_dtp = DV_TYPE_OF (datum->_.lit.val);
+                      {
+                        if (uname_xmlschema_ns_uri_hash_boolean != datum->_.lit.datatype)
+                          restr_set &= ~SPART_VARR_IS_BOOL;
+                        datum_dtp = DV_TYPE_OF (datum->_.lit.val);
+                      }
                     if (!((DV_LONG_INT == datum_dtp) || (DV_DOUBLE_FLOAT == datum_dtp) || (DV_SINGLE_FLOAT == datum_dtp) || (DV_DATETIME == datum_dtp)))
                       restr_set &= ~SPART_VARR_LONG_EQ_SQL;
                     if (!(DV_LONG_INT == datum_dtp))
```

**Comment by openlink** [comment] 2016-03-03 13:01
fix has been committed to develop/7 branch

**Closed as completed by openlink** 2016-03-03 13:01 UTC
