### ISSUE TITLE
CPU load goes up to 100% when Virtuoso runs its look up processing

### ISSUE THREAD

**Issue by ieyasu109** [openlink/virtuoso-opensource#714] opened 2018-02-21 01:37 UTC
After we updated Virtuoso from v7.2.1 to v7.2.4.2, 
the CPU load became to go up to 100% when we run its look up processing via SPARQL.

With Virtuoso v7.2.4.2, the CPU load goes up to 100% during the look up processing is running,
and it takes 3 times longer than v7.2.1.
The number of stored data is 2000.

The spec of server is as follows:
 - CPU: Intel Xeon X5670 2.93GHz
 - RAM: 7.5GB

It is really appreciated if you kindly give us advice regarding the suspected root causes
and the way to avoid this issue.

The following is our query to run SPARQL look up processing.

```sparql 
sparql 
prefix odp: <http://www.example.com/LOD/ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix dc: <http://purl.org/dc/elements/1.1/> 
prefix dct: <http://purl.org/dc/terms/> 
prefix schema: <http://schema.org/> 
select ?s ?label ?url ?locality ?description ?categoryURI ?facilityURI ?outdoor ?charge ?reservation
 ?ageFrom ?ageTo ?location ?promoter ?listImage ?detailImage ?date1 ?time1 ?date2 ?time2 ?created ?modified
  from <http://www.example.com/LOD/spot>
  from <http://www.example.com/LOD/place>
 where {
  ?s a odp:Spot ;
    odp:spot-type <http://www.example.com/LOD/sp/type/2> ;
    rdfs:label ?label ;
    odp:spot-category ?categoryURI ;
    odp:locality ?locality ;
    odp:location ?location ;
    dct:created ?created ;
    dct:modified ?modified ;
    odp:outdoor ?outdoor ;
    odp:charge ?charge ;
    odp:reservation ?reservation ;
    odp:age/odp:fromAge ?ageFrom ;
    odp:age/odp:toAge ?ageTo .
    OPTIONAL {
      ?s schema:url ?url .
    }
    OPTIONAL {
      ?s odp:listImage ?listImage .
    }
    OPTIONAL {
      ?s odp:detailImage ?detailImage .
    }
    OPTIONAL {
      ?s odp:openDate1 ?date1 .
    }
    OPTIONAL {
      ?s odp:openTime1 ?time1 .
    }
    OPTIONAL {
      ?s odp:openDate2 ?date2 .
    }
    OPTIONAL {
      ?s odp:openTime2 ?time2 .
    }
    OPTIONAL {
      ?s odp:promoter ?promoter .
    }
    OPTIONAL {
      ?s odp:facility ?facilityURI .
      ?location odp:facility ?facilityURI .
    }
    OPTIONAL {
      ?s dc:description ?description .
    }
}
```

**Comment by TallTed** [comment] 2018-02-21 21:42
First guess is that your INI file has not been [tuned properly for available memory (which is not equal to installed memory)](http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning) ... though it seems unlikely the default settings would lead to such issues with only 2000 quads (is that number correct?).

Are you using Virtuoso Open Source (VOS) or Enterprise Edition?  If the latter, a Support Case may be a more appropriate path to resolution.

What's the full Virtuoso version as reported by `virtuoso-t -?` for VOS or `virtuoso-iodbc-t -?` for Enterprise Edition?  It's best to provide the first paragraph of output (everything before the `Usage:` section).

**Comment by ieyasu109** [comment] 2018-02-21 23:44
The setting of the INI file (/usr/local/virtuoso/var/lib/virtuoso/db/virtuoso.ini) is as follows.

```ini
  ...
;; Note the default settings will take very little memory
;; but will not result in very good performance
;;
NumberOfBuffers          = 611669
MaxDirtyBuffers          = 458752
```

We are using Virtuoso Open Source (VOS). The result of `virtuoso-t -?` is as follows.

```sh
# cd /usr/local/virtuoso/bin/
# ./virtuoso-t -?
Virtuoso Open Source Edition (Column Store) (multi threaded)
Version 7.2.4.2.3217-pthreads as of Nov  8 2017
Compiled for Linux (x86_64-unknown-linux-gnu)
Copyright (C) 1998-2016 OpenLink Software
  ...
```

**Comment by timhaynesopenlink** [comment] 2018-02-22 12:05
Hi,
Ultimately the way to solve this is to generate an explain output of the SPARQL query: see https://medium.com/virtuoso-blog/generate-sparql-query-compilation-report-from-a-virtuoso-sparql-endpoint-5a54f73ebdd0

Meanwhile, one thing to think about: as a general rule, queries run faster if you eliminate the greatest number of rows in the earliest constraint. For example,
```
where {
  ?s a odp:Spot ;
    odp:spot-type <http://www.example.com/LOD/sp/type/2> ;
```

is it possible to have that odp:spot-type and *not* be an odp:Spot? That might be redundancy, but it is likely to reduce the rows fast. That could be OK.

However,
```
 rdfs:label ?label ;
    odp:spot-category ?categoryURI ;
```
By the time we get down here constraining to odp:Spot and a particular odp:spot-type etc, if there are more triples concerning rdfs:label than are in that odp:spot-category, maybe you'd do better to flip those two lines around. Worth trying and see if it makes any difference to the query execution plan above.

HTH

**Comment by TallTed** [comment] 2018-02-22 17:37
The INI file settings and Virtuoso version look OK.

Starting queries with `rdf:type` (or `a`) patterns can lead to a lot of extra processing.  Assuming that `odp:spot-type` and `odp:spot-category` apply only to resources that are `rdf:type odp:Spot` (and so will inherently serve the same purpose as `?s a odp:Spot`), I suggest you try removing the `?s a odp:Spot` from your query.  If other `rdf:type`s may have these attributes, you could move the `?s a odp:Spot` to the bottom.

**Comment by ieyasu109** [comment] 2018-02-27 00:01
Thank you for the advice.
However, despite the same SPARQL we want to know why the lookup performance got worse.
Is there information such as incompatibility and a doubtful cause, etc?

**Comment by TallTed** [comment] 2018-02-27 15:29
@ieyasu109 It is difficult to impossible to say what caused your specific experience, unless you provide much more information about your data (e.g., do you really only have 2000 triples/quads stored in Virtuoso?), the complete configuration files (not just the few lines excerpted above) for the two instances, more details about the host environment(s) (such as whether the 7.5 GB mentioned is the total RAM installed, or just the amount available to Virtuoso, or something else), and more.

A starting point for such analysis is often [EXPLAIN and/or PROFILE output](http://vos.openlinksw.com/owiki/wiki/VOS/VirtTipsAndTricksAnalyzingSPARQLQuery). Note that this output is not designed for the average user, and is usually analyzed by our development team.

**Comment by ieyasu109** [comment] 2018-03-01 09:23
@TallTed  Thank you for you advice.
Following the suggeted procedure, I obtained respective information.
Each of the followings is the information obtaining procedure:

  1. Translate a SPARQL query into the correspondent SQL;
  2. Generate compilation plan of an SQL query;
  3. Generate compilation and execution plan of an SQL query.

Could you please check the information?
I sincerely wish this information helps our troubleshooting.

[full_explain_and_profile_plans_.txt](https://github.com/openlink/virtuoso-opensource/files/1770538/full_explain_and_profile_plans_.txt)

**Comment by TallTed** [comment] 2018-03-01 15:57
@ieyasu109 - The `EXPLAIN()` and `PROFILE()` output is only part of the picture. To be clear, I also need --

1. Confirmation of total machine RAM, as well as RAM available to Virtuoso
2. The complete INI file for the active Virtuoso 7.2.4.2 instance
3. The complete INI file for the previous Virtuoso 7.2.1 instance, if different from (3)
4. An accurate count of quads, produced by output of --
   ```
   SPARQL SELECT ( COUNT(*) AS ?NumberOfQuads ) 
   WHERE { ?s ?p ?o } ;
   ```
5. A new request -- output of the following SQL query on the active Virtuoso 7.2.4.2 instance --
   ```
   STATUS();
   ```

**Comment by ieyasu109** [comment] 2018-03-02 04:11
Here is the answers for your confirmation.
Thank you for your continuous support.

1.Confirmation of total machine RAM, as well as RAM available to Virtuoso The implemented RAM size is 7.5GB.
And based on the result of "free" command with Virtuoso being in stop status, we suppose the memory which can be assigned to Virtuoso is 7.1GB at maximum.
(Please see the line "-/+ buffers/cache" below.)
```
# service virtuoso stop
Stopping OpenLink Virtuoso Open-Source Edition: virtuoso.
# free -tm
             total       used       free     shared    buffers     cached
Mem:          7337       1672       5665          0        315       1127
-/+ buffers/cache:        229       7108
Swap:         5859          0       5859
Total:       13197       1672      11524

# service virtuoso  start
Starting OpenLink Virtuoso Open-Source Edition: virtuoso.
# free -tm
             total       used       free     shared    buffers     cached
Mem:          7337       4219       3118          0        315       1041
-/+ buffers/cache:       2861       4476
Swap:         5859          0       5859
Total:       13197       4219       8978

# ps aux | grep virtuoso-t
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
virtuoso  2175  7.3 35.9 5787840 2698080 ?     Ssl  10:39   0:06 /usr/local/
virtuoso/bin/virtuoso-t -c virtuoso +wait
root      2220  0.0  0.0 107460   912 pts/0    S+   10:41   0:00 grep
virtuoso-t
```

2.The complete INI file for the active Virtuoso 7.2.4.2 instance Here I attached the INI file.
This is same as the one which we used in v7.2.1 environment.

[virtuoso.ini](https://github.com/openlink/virtuoso-opensource/files/1773689/virtuoso.ini.txt)

4.An accurate count of quads, produced by output of -- 5.A new request -- Here I attached the result of the confirmation above..
Could you please kindly check them?

[No.4_and_No.5_result.txt](https://github.com/openlink/virtuoso-opensource/files/1773690/No.4_and_No.5_result.txt)

**Comment by TallTed** [comment] 2018-03-02 16:06
OK. It generally makes sense to leave a bit of wiggle room in RAM allocations, so please change —

    NumberOfBuffers          = 611669
    MaxDirtyBuffers          = 458752

— to —

    NumberOfBuffers          = 595000
    MaxDirtyBuffers          = 446250


Everything else looks OK to this point.  There are many possibilities remaining.  As I'm sure you can understand, it's difficult to compare two things while only seeing one.

* Knowing little of the history of this DB, it may be worthwhile to run a `backup ‘/dev/null’ ;` (through iSQL) to check for corruption.  If found, rebuilding the DB by doing a `+crash-dump` followed by `+restore-crash-dump` is strongly recommended.
* Rebuilding the DB by doing a `+backup-dump` followed by `+restore-backup` may be worthwhile anyway.
* We can learn more by now re-executing your original query, and running `status();` in a parallel iSQL instance while that query is in process.

**Comment by timhaynesopenlink** [comment] 2018-03-02 17:03
Hi,

In addition to TallTed's comments, I've spoken with development and have a couple of further angles of attack.

First: there are (at least) 3 ways of executing a SPARQL query: there's commandline `isql` and there's two HTTP endpoints at `/sparql` and `/sparql-auth`. Does your query run equally slowly in both isql and either of the HTTP endpoints (logging in as dba in the case of `/sparql-auth`)?

Second: 7.2.4.2 is the stable branch and comparatively old. Would it be possible for you to 
```git checkout develop/7```
and build off the latest develop branch instead?
We're cooking-up another release so this should not be particularly unstable at the moment. Additionally the newer version will have a nicer way to run `explain` direct from the `/sparql` endpoint.

Thanks

**Comment by ieyasu109** [comment] 2018-03-09 00:06
@TallTed @timhaynesopenlink Thank you for your advice.

1. We changed INI file as below.
   ```
   NumberOfBuffers          = 595000
   MaxDirtyBuffers          = 446250
   ```
2. No error occured by `backup'/dev/null'` of iSQL,
so that we did not rebuild DB with `+restore-crash-dump`,
but rebuild it with `+restore-backup`.

By dealing as above, the problem was not solved.
During execution QUERY, it takes 58 seconds, CPU utilization is always 100%.
We attached the result of `STATUS()` output while execution QUERY.

[status_result.txt](https://github.com/openlink/virtuoso-opensource/files/1795183/status_result.txt)

**Comment by ieyasu109** [comment] 2018-03-12 04:43
@timhaynesopenlink Thank you for the advice.
The confirmed sparql is executed in two ways, isql and JDBC driver.

```java
  Class.forName("virtuoso.jdbc4.Driver");
  String url = "jdbc:virtuoso://localhost:1111";
  Connection conn = DriverManager.getConnection(url, user, pass);
  Statement st = conn.createStatement();
  PreparedStatement ps;
  ParameterMetaData pm;
  st.executeUpdate("sparql");
```

Both isql and JDBC driver are slow.
HTTP endpoints are not used.

`git checkout develop / 7` is not yet executed, but I will consider it.

**Comment by ieyasu109** [comment] 2018-04-24 07:50
As per your advice, we are now confirming the behavior of the latest develop branch of Virtuoso.
Could you please tell us following 2 points:

1. We are considering to use v7.2.1 for Virtuoso engine, beside using develop7 branch for JDBC driver.
   Does this combination work without any contradiction or confliction?
   
   Our intention of the combination above is as follows:
     - Virtuoso engine of v7.2.4.2 involves CPU load issue in our usage.
     - JDBC driver of v7.2.1 involves memory leak problem related to the finalize implementation.
     - JDBC driver of v7.2.4.2 involves the problem related to date acquisition as mentioned in issue#709.

   The precise versions of the Virtuoso engine and the JDBC driver are as follows.

```
     # /usr/local/virtuoso/bin/virtuoso-t -?
     Virtuoso Open Source Edition (Column Store) (multi threaded)
     Version 7.2.1.3214-pthreads as of Aug 26 2016
     Compiled for Linux (x86_64-unknown-linux-gnu)
     Copyright (C) 1998-2015 OpenLink Software
```
```
     # java -jar virtjdbc4.jar
     OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.0 [Build 3.108]
``` 

2. Are there any similar questions or cases, which have encountered same kind CPU high load problem or any performance degradation related to the version upgrading from 7.2.1 to 7.2.4.2 ?
   If any, it is really appreciated if you tell us about it and hopefully with the solution in that case.

**Comment by TallTed** [comment] 2018-04-24 16:29
1. There should be no conflict with using the more recent JDBC driver against the older Virtuoso engine.  That said, upgrading the engine remains recommended, and will be more so with the upcoming stable VOS release.

   Please note that if you're running current Java (i.e., Java 8 a/k/a 1.8.x), you should be using `virtjdbc4_2.jar` rather than `virtjdbc4.jar`; version output should show `OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.2`. 

   (If using Java 7, you should use `virtjdbc4_1.jar` [version output `OpenLink Virtuoso(TM) Driver for JDBC(TM) Version 4.1`]; Java 6 is best with `virtjdbc4.jar`.  All three of these -- `virtjdbc4_2.jar`, `virtjdbc4_1.jar`, and `virtjdbc4.jar` -- have the same classname, `virtuoso.jdbc4.Driver`.)

2. I am not aware of any other 7.2.1-to-7.2.4.2 upgrade scenario that has resulted in a CPU load issue similar to what you've described.

3. Re-reading your SPARQL query, I wonder if a small optimization might make a difference for you.  Your `WHERE` clause currently starts with `?s a odp:Spot`.  I'm wondering whether this may be effectively redundant -- that is, whether the subsequent `odp:spot-type <http://www.example.com/LOD/sp/type/2>` and `odp:spot-category ?categoryURI` might not force the `rfd:type`, because only instances of  `odp:Spot` have `odp:spot-type` and `odp:spot-category`.  If so, removing the 
`a odp:Spot` pattern can improve performance, for a variety of reasons.

   To be clear, I'm suggesting you try changing this line of your query, as initially posted --
   ```sparql
   ?s a odp:Spot ;
   ```
   -- to this --
   ```sparql
   ?s # a odp:Spot ;
   ```

   (There are other tactics that may be tried, if other entity types might have the `odp:spot-type` and/or `odp:spot-category` attributes.)

**Comment by ieyasu109** [comment] 2018-04-25 08:03
Thank you for your advices.
I understand that the recent several updates of JDBC don't involve any modification related to the I/F toward Virtuoso engine.
Is my understanding correct?
Then I shall continue the confirmation of the combination which I mentioned above.

By the way, I have one more question related to your advice.
You adviced to change the query ``?s a odp:Spot ;`` to ``?s # a odp:Spot ;``.
Could you tell me the meaning of the letter "#"?
I'm trying to look for the meaning, but not found yet...

**Comment by TallTed** [comment] 2018-04-25 13:44
@ieyasu109 

The inserted ` #` makes the remainder of that line a comment.

The effect is the same as changing these two lines —
```sparql
  ?s a odp:Spot ;
    odp:spot-type <http://www.example.com/LOD/sp/type/2> ;
```
— to these two —
```sparql
  ?s 
    odp:spot-type <http://www.example.com/LOD/sp/type/2> ;
```
— or this one —
```sparql
  ?s odp:spot-type <http://www.example.com/LOD/sp/type/2> ;
```

**Comment by ieyasu109** [comment] 2018-04-27 01:49
Thanks for the advice.
I corrected the query as indicated, the effect was confirmed.
Because Java is using 7, the JDBC driver will use `virtjdbc4_1.jar`.

**Comment by TallTed** [comment] 2018-04-27 14:15
@ieyasu109 - When you say, "the effect was confirmed," do you mean, that the CPU spike was resolved by removing the `a odp:Spot` clause?  If so, would you say that this issue may be considered Closed?

**Comment by ieyasu109** [comment] 2018-05-08 08:45
Yes. You may close it.
Thank you very much.

**Closed as completed** 2018-05-08 14:01 UTC
