### ISSUE TITLE
REGRESSION: "LOAD <> INTO <>" is broken in 6.1.7 and develop/7 again

### ISSUE THREAD

**Issue by indeyets** [openlink/virtuoso-opensource#68] opened 2013-07-23 13:33 UTC
`LOAD <file:///path/to/file> INTO <http://example.org/graph>` results in the following error:

"Virtuoso 22023 Error SR008: Function sprintf needs an integer as argument 3, not an arg of type VARCHAR (182)"

**Comment by imitko** [comment] 2013-07-24 09:44
please try with recent changes in develop/7, i can't reproduce using the current state of the branch.

**Comment by indeyets** [comment] 2013-07-24 09:48
@imitko I just did. Still getting it. full message looks like this:

```
SPARQL endpoint error: Virtuoso 22023 Error SR008: Function sprintf needs an integer as argument 3, not an arg of type VARCHAR (182)

SPARQL query:
define sql:big-data-const 0 
#output-format:application/sparql-results+json
define sql:signal-void-variables 1 define input:default-graph-uri <http://grids.by/types> LOAD <file:///Users/indy/Documents/Sources/_mine/grids.by/core/app/rdf-schemas/cache/www.w3.org/2000/01/rdf-schema> INTO <http://grids.by/types>
```

**Comment by openlink** [comment] 2013-07-24 12:11
I just pushed fix for this issue to both develop/6 and develop/7 branches.

**Comment by indeyets** [comment] 2013-07-24 12:17
@openlink thanks! I'll check it. do you know, that you can use `gh-123` syntax in commit messages? Then commits will appear here in bugtracker automatically

**Comment by indeyets** [comment] 2013-07-24 12:38
`develop/7` — CONFIRMED

**Comment by indeyets** [comment] 2013-07-24 13:33
`virtuoso-6.1.7` (from sourceforge) + fd538a97 — CONFIRMED

**Closed as completed** 2013-07-25 10:13 UTC

**Comment by abondoa** [comment] 2013-10-21 19:04
I get a similar error in virtuoso 7 on windows 7 64 bits. The query:

```
define input:storage <http://extbi.cs.aau.dk/mappings/quad_storage/default>

prefix mrk: <http://extbi.cs.aau.dk/ontologies/agriculture#> 

select *
where {?S mrk:markkortid ?markkortid.
?S ?P ?O .
FILTER(?markkortid="191430") }
```

Leads to the following error:

```
Virtuoso 22023 Error SR008: Function sprintf needs an integer as argument 2, not an arg of type VARCHAR (182)

SPARQL query:
define sql:big-data-const 0 
#output-format:text/html
define input:storage 

prefix mrk:  

select *
where {?S mrk:markkortid ?markkortid.
?S ?P ?O .
FILTER(?markkortid="191430") }
```

**Comment by indeyets** [comment] 2013-10-21 19:05
@abondoa this one is fixed in develop/7 branch already
